### ISSUE TITLE
Conflicting dependencies on Raspbian GNU Linux version 11 (Bullseye)

### ISSUE THREAD

**Issue by MartinDude** [TomWhitwell/SlowMovie#103]
I was able to successfully run the installation on Raspbian GNU Linux version 10 (Buster).
But when I try the exact same installation script on the latest Raspberry Pi OS (GNU Linux version 11 - Bullseye) it crashes.

**** SEE MY FOLLOW-UP COMMENT BELOW FOR THE FIX *****

**Describe the problem**
Getting the following error message:
ERROR: Cannot install -r /home/pi/SlowMovie/Install/requirements/txt (line 5) and waveshare-epd 0.0.0 (from git+https://github.com/waveshare/e-Paper.git#egg=waveshare-epd&subdirectory=RaspberryPi_JetsonNano/python) because these package versions have conflicting dependencies.

The conflict is cause by:
      The user requested waveshare-epd 0.0.0 (from git+https://github.com/waveshare/e-Paper.git#egg=waveshare-epd&subdirectory=RaspberryPi_JetsonNano/python)
      omni-epd 0.2.4 depends on waveshare-epd 0.0.0 (from git+https://github.com/waveshare/e-Paper.git#subdirectory=RaspberryPi_JetsonNano/python&egg=waveshare-epd)

To fix this you could try to:
1. loosen the range of package version you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResulotionImpossible: for help visit https://pip.pypa.io/latest/user_guide/#fixing-conflicting-dependencies

**Steps to Reproduce**
Install latest Raspberry Pi OS from scratch (Bullseye)
Launch automatic SlowMovie installation:
> bash <(curl https://raw.githubusercontent.com/TomWhitwell/SlowMovie/main/Install/install.sh)

**Platform Information** 
RaspberryPi Zero 2W
OS = Raspbian GNU/Linux version 11 (Bullseye)
Python3 = 3.9.2

**Comment by MartinDude** [comment]
Looked more closely at the details and was able to fix the problem.
It is a very minor fix to be applied to the file 'SlowMovie/Install/requirements.txt'
I has to do with the order in which # arguments are specified.
I suspect that with RaspberryPi OS 11 (bullseye) the requirements verification got a tad more strict than before. OS 10 (buster) did not complain about the order mismatch, but 11 (bullseye) does...

Here is the fix for the Automatic Installation.
[requirements.txt](https://github.com/TomWhitwell/SlowMovie/files/7523495/requirements.txt)

Step 1 - Initiate automatic installation 
  > bash <(curl https://raw.githubusercontent.com/TomWhitwell/SlowMovie/main/Install/install.sh)
  
Step 2 - Manually edit requirements file
    Manually edit file 'requirements.txt' located in folder SlowMovie/Install
    Edit 4th line to read as follows:
    git+https://github.com/waveshare/e-Paper.git#subdirectory=RaspberryPi_JetsonNano/python&egg=waveshare-epd
    It is a very easy edit (switching the order of the #subdirectory and #egg portions of the line.)
    Attaching the fixed requirements.txt file as reference.

Step 3 - Re-Run the installation locally this time
    > bash SlowMovie/Install/install.sh
    Select option 1

Step 4 - Re-run installation locally for the service portion
    > bash SlowMovie/Install/install.sh
   Select option 2

That's it!

**Comment by whiteenvelope** [comment]
Thanks so much for the fix, I just got this error too doing this project for the first time and it fixed it too! Thanks, I love this project.

**Comment by robweber** [comment]
Nice work hunting this down. That's interesting that these are seen as two different versions just based on the URL like that.
