### ISSUE TITLE
Need help using Waveshare 7.8in EPD

### ISSUE THREAD

**Issue by grooverkm** [TomWhitwell/SlowMovie#11]
Sorry in advance for any noob questions, I'm a beginner.  Trying to use a RaspberryPi 4 with a waveshare 7.8in HD display.  It is not in the wave share-epd library, but I have been able to run a demo using the file from repository at [https://github.com/waveshare/IT8951-ePaper](https://github.com/waveshare/IT8951-ePaper) and the correct VCOM value for my screen.
I don't know how to add this as driver for SlowMovie to see it.  Does anyone have any pointers please?  Apologies if I should be asking these questions elsewhere.

**Comment by scsibug** [comment]
Another option is to compile the C version of the code at https://github.com/waveshare/IT8951, and use a temporary file in conjunction with that executable to display images.  It certainly simplifies the Python dependencies.

I do something similar in a picture frame using the 7.8" HD screen - I convert images from flickr using python, but have a cron job that actually performs the display using the executable provided by Waveshare (https://github.com/scsibug/pictureframe)

**Comment by grooverkm** [comment]
Thanks for the pointer.  Struggled to use the waveshare driver in a python wrapper as it is way above my competence level, so decided to replace it with the 7in5_V2 screen.  Everything working as expected now apart from some fine tuning, and I’ll use the 7.8in5 for something else.

Thanks again.
