### ISSUE TITLE
Beginner difficulty

### ISSUE THREAD

**Issue by TimiRose** [TomWhitwell/SlowMovie#12]
Hi, one more beginners question. I´ve built some of Toms amazing modules, and thought this should be just as easy and being completly new to this wriggled my way through to getting the testscreen to work. But now I can´t get any further.
This is my error:

pi@raspberrypi:/home/SlowMovie $ python helloworld.py
Traceback (most recent call last):
  File "helloworld.py", line 30, in <module>
    from waveshare_epd import epd7in5_V2
ImportError: No module named waveshare_epd

Many thanks for any help!
Tim

**Comment by TimiRose** [comment]
Hi I got one step further, but still having problems. I am using noobs but then there seems to be something wrong with the libraries as I understand it. 

/home/SlowMovie/Videos/test.mp4
Traceback (most recent call last):
  File "helloworld.py", line 69, in <module>
    pil_im = Image.open("grab.jpg")
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: 'grab.jpg'

and 
/home/SlowMovie/Videos/test.mp4
Traceback (most recent call last):
  File "helloworld.py", line 66, in <module>
    generate_frame(inputVid, 'grab.jpg', msTimecode, width, height)
  File "helloworld.py", line 25, in generate_frame
    .run(capture_stdout=True, capture_stderr=True)
  File "/usr/local/lib/python2.7/dist-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

Greetings, Tim

**Comment by MattBrowne1** [comment]
I had the same issue.  Resolved it by doing.....

pip uninstall ffmpeg
pip uninstall ffmpeg-python
pip install ffmpeg-python

**Comment by NickAnsy** [comment]
I can’t thank you enough. 
Can’t even begin to explain the struggles with this. 
Thank you thank you!

**Comment by qubist** [comment]
This also worked for me! Thanks!!
