### ISSUE TITLE
Question regarding SSH

### ISSUE THREAD

**Issue by vitaboy89** [TomWhitwell/SlowMovie#121]
**Describe the problem**
I have the SlowMovie player up and running, but it only works when I am connected through SSH on my mac terminal. Once I quit the terminal or end the SSH session it stops working. Is there any way to work around this? Or maybe I'm missing something? Ideally, my raspberry pi would run by itself and the video file will just loop at the interval I set. If anyone has any solutions it would be greatly appreciated.

**Platform Information** 
Raspberry pi 3b+ , 32 bit Raspberry pi OS from raspberry pi imager, python3, my mac runs Montery

**Comment by robweber** [comment]
How did you install the program? Was it manually or using the automated installer script? If you review the readme file you'll see instructions for running the script as a service, which will allow it to run without SSH or access to the terminal. 

The install script has an option to setup the service for you as well.

**Comment by j2r2jones** [comment]
robweber's comment is probably the best option. If you wanted some logs you could always run using nohup ./slowmovie.py &

**Comment by vitaboy89** [comment]
@robweber @j2r2jones thank you guys! I reinstalled the program through the automated script and also installed it as a service and it worked automatically now. 

I have another question (I'm really inexperienced with code, sorry in advance for stupid questions):
How do I access the video directory and the slowmovie.conf? I didn't really understand that part in the Readme. 
What I want is to switch to another video and also set custom delay, increments and loop settings to automatically happen when I boot the Raspberry Pi.

Thanks in advance,
Duy

**Comment by robweber** [comment]
The `slowmovie.conf` file is something you have to create manually but can be used to set all of those variables so it loads at start. You can put the file anywhere you want but just making it within the SlowMovie folder is fine. Once created you'll need to edit the [service file](https://github.com/TomWhitwell/SlowMovie/blob/main/slowmovie.service#L7) to include `-c /location/to/file.conf`. This will tell the service at startup to read variables from that file. 

As far as the file itself you can use [any argument available](https://github.com/TomWhitwell/SlowMovie#running-from-the-shell) to the main program. An example might be: 

```
directory = /path/to/videos
delay = 400
increment = 10
```

Hopefully that helps.

**Comment by missionfloyd** [comment]
> How do I access the video directory and the slowmovie.conf?

You'll find both in `/home/pi/SlowMovie`. You only need to edit the service if you have the config file in a different folder.
To copy videos to it, you'll need an SFTP client such as cyberduck.

@robweber Does that work? We're using `-c` for contrast. It's a bit redundant, though, since omni-epd does it as well.

**Comment by robweber** [comment]
No it doesn't. I didn't check the parser and confused it with a different lib. I'll edit the above to avoid confusion.

**Comment by vitaboy89** [comment]
Thanks for all the help everyone! I got it working in service mode now. Using Cyberduck helped immensely! Closing this issue for now. Cheers everyone!
