### ISSUE TITLE
Issue with Automated install

### ISSUE THREAD

**Issue by tmoistner** [TomWhitwell/SlowMovie#123]
After running the command for automated installation and running python3 slowmovie.py; I'm left with the following error -

Traceback (most recent call last):
  File "/home/pi/SlowMovie/slowmovie.py", line 22, in <module>
    from PIL import Image, ImageEnhance
  File "/home/pi/.local/lib/python3.9/site-packages/PIL/Image.py", line 45, in <module>
    from . import (
ValueError: source code string cannot contain null bytes

I've verified all of the packages installed correctly. Any ideas on what could be causing this?

**Comment by qubist** [comment]
Interesting... Googled the error: https://stackoverflow.com/questions/31233777/python-source-code-string-cannot-contain-null-bytes

Seems like it could be a problem with the way the file downloaded. How did you verify the packages installed correctly? Can you open `/home/pi/.local/lib/python3.9/site-packages/PIL/Image.py` and see what's inside?

**Comment by tmoistner** [comment]
I'm guessing it was just an issue with my environment. I reinstalled everything by hand and it's working.
