### ISSUE TITLE
More control features while player is running 

### ISSUE THREAD

**Issue by TmCrafz** [TomWhitwell/SlowMovie#127]
I have running SlowMovie player on my raspberry pi as service for a while now. It's working fine so far. Now I'm looking for more functions to control the player while it is running. For example:
- Jump to next File
- Jump X seconds/X Minutes/X Frames forward/backwards
- Pause
Is there any plan to implement something similar or would a pull request accepted which extendeds the player with such functions?

**Comment by qubist** [comment]
I think @robweber has a pretty evolved fork of the repo that has features like this provided through a networked GUI: https://github.com/robweber/vsmp-plus

**Comment by robweber** [comment]
That project would be a good place to start, there may be other forks with similar functionality too. We're trying to very consciously avoiding [big diversions from core functionality](https://github.com/TomWhitwell/SlowMovie#contributing) to maintain the spirit of this project. It's a fine line but keeps from feature creep.

**Comment by TmCrafz** [comment]
Thanks, I will checkout the forks. I also just realized that just stopping the player is equivalent to pausing the movie. And when starting the player it is continuing the playback by default. So at least that future is implemented already

**Comment by TmCrafz** [comment]
I created an application which makes it possible to control SlowMovie over an GUI from inside the browser. It is not a fork, but a wrapper around SlowMovie. It is possible to select from the Videos inside your Video folder and Pause/Stop or Start from specific frames and more. 

If someone is interested to take a look into the project you can find it here:
[SlowMovie Web GUI](https://github.com/TmCrafz/SlowMovieWebGUI)

Everyone who want can join the project or give feedback.
