### ISSUE TITLE
No module named 'omni_epd' ,please help me!

### ISSUE THREAD

**Issue by afly-8** [TomWhitwell/SlowMovie#128]
```
:~/SlowMovie $ pip3 install git+https://github.com/robweber/omni-epd.git#egg=omni-epd
Looking in indexes: http://pypi.douban.com/simple/, https://www.piwheels.org/simple
Collecting omni-epd
  Cloning https://github.com/robweber/omni-epd.git to /tmp/pip-install-zbd_ofbi/omni-epd_0309d98943b74018b214bfffeb06e101
  Running command git clone -q https://github.com/robweber/omni-epd.git /tmp/pip-install-zbd_ofbi/omni-epd_0309d98943b74018b214bfffeb06e101
  error: RPC 失败。HTTP 429 curl 22 The requested URL returned error: 429
  fatal: 读取节标题 'shallow-info' 出错
WARNING: Discarding git+https://github.com/robweber/omni-epd.git#egg=omni-epd. Command errored out with exit status 128: git clone -q https://github.com/robweber/omni-epd.git /tmp/pip-install-zbd_ofbi/omni-epd_0309d98943b74018b214bfffeb06e101 Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement omni-epd (unavailable)
ERROR: No matching distribution found for omni-epd (unavailable)
``` 

```
~/SlowMovie $ python3 slowmovie.py
Traceback (most recent call last):
  File "/home/xiaole/SlowMovie/slowmovie.py", line 24, in <module>
    from omni_epd import displayfactory, EPDNotFoundError
ModuleNotFoundError: No module named 'omni_epd'

```

**Comment by robweber** [comment]
I just did an install with `pip3 install git+https://github.com/robweber/omni-epd.git#egg=omni-epd` to confirm it's not a Python problem. 

I see you're getting HTTP Error 429, which corresponds to [Too Many Requests](pip3 install git+https://github.com/robweber/omni-epd.git#egg=omni-epd) issue. Might just be a problem with your internet connection or something. I'd advise retrying at a different time of day. Another option might be to just install omni-epd [from scratch](https://github.com/robweber/omni-epd#install); although if you can't clone the repo that might be a problem as well.

**Comment by afly-8** [comment]
Thank you for your answer. I think I know what my problem is. I'm in inland China. Maybe some resources can't be obtained completely. Then my solution is to send an agent to raspberry pie, but I also encounter many problems and still can't download resources. So I want you to ask. Is there any other way? Thank you!

**Comment by afly-8** [comment]
I changed other networks and downloaded and installed again. Now it's finally ready. It's OK to install at different times. Thank you. The problem is solved!
