### ISSUE TITLE
Dark / Streaking Display

### ISSUE THREAD

**Issue by lampeight** [TomWhitwell/SlowMovie#134]
Hi all, I have been having a problem with the script since using the updater tool.

The setup was working fine when I originally set it up in 2020 based on the original manual instructions. After seeing it gather dust for too long, I've set it back up and updated the script using the the tool.

Since then, I cannot re-create the same quality images as before. All images are either incredibly dark or incredibly smeared. I have changed the Display config switch as highlighted in another post but this doesn't seem to have made a difference. See below:

![PXL_20220914_135717219](https://user-images.githubusercontent.com/25267550/190178610-2d7b5f53-9b67-4e84-b421-f21d5db79a98.jpg)
![PXL_20220914_135424944 MP](https://user-images.githubusercontent.com/25267550/190178620-26f628ad-368c-4593-a7d4-e954d917eb68.jpg)

I'm running on an original RPi Model B with a Waveshare display. I haven't made any changes to the setup other than updating it. Has anyone else encountered anything similar or can help me troubleshoot the behavior?

**Comment by robweber** [comment]
Without using SlowMovie at all can you get any images to show up on the display? Seems like either a driver problem, a connection problem, or hardware problem.

**Comment by missionfloyd** [comment]
Try an earlier driver version. I've been using [this one](https://github.com/waveshare/e-Paper/tree/b36cfab0ea336673982640ea21969e5a54714448).

```
pip3 install -U "git+https://github.com/waveshare/e-Paper.git@b36cfab0ea336673982640ea21969e5a54714448#subdirectory=RaspberryPi_JetsonNano/python&egg=waveshare-epd"
```

**Comment by lampeight** [comment]
Thanks, all. Going to try a fresh re-format and install just to make sure it's not any lingering outdated drivers that are causing the issue. Will report back.

**Comment by lampeight** [comment]
After a full reformat, manual re-install, driver rollback and even switching to an alternative RPi, I'm still getting poor quality images on both Display Config A and B settings. I've tried running the House of Dust example too and no joy. Picture is either extremely light or extremely dark with smearing. Sounds like either my ribbon cable or my display is busted unfortunately.

**Comment by lampeight** [comment]
Was just messing around with this today and managed to get it working by using the "b36cfa" commit from above. Not hardware-based at all then. Shows that somewhere along the line, an update to the Waveshare driver has broken compatibility for 7.5" V2 displays.

**Comment by TomWhitwell** [comment]
I have just had a similar problem with my og display - used the update script to add full screen, not have big streaks ![image](https://user-images.githubusercontent.com/1890544/211767887-932ac15e-68ef-45f5-90a1-16b1b6cd587f.jpeg)

**Comment by robweber** [comment]
The updater script will also update other libraries - like the Waveshare library. Have you tried reverting it to something like the one missionfloyd suggested? I've had issues with the most up to date versions of the Waveshare repo and usually do a rollback. Seems to be something software related on their end. 

> Try an earlier driver version. I've been using [this one](https://github.com/waveshare/e-Paper/tree/b36cfab0ea336673982640ea21969e5a54714448).
> 
> ```
> pip3 install -U "git+https://github.com/waveshare/e-Paper.git@b36cfab0ea336673982640ea21969e5a54714448#subdirectory=RaspberryPi_JetsonNano/python&egg=waveshare-epd"
> ```
> 
> And try the waveshare [example](https://github.com/waveshare/e-Paper/tree/master/RaspberryPi_JetsonNano/python/examples) script.

**Comment by TomWhitwell** [comment]
OK that worked, thank you

Is there any way to adjust the installer script so this works for new users, and/or should I be raising this in the waveshare repo? 

![image](https://user-images.githubusercontent.com/1890544/211846647-9d29a7e2-2ae2-4c8b-8362-d9b42dd95ac1.jpeg)

**Comment by robweber** [comment]
Going to close this out since @missionfloyd has fixed this in the Waveshare lib.
