### ISSUE TITLE
Inky Impression

### ISSUE THREAD

**Issue by TomWhitwell** [TomWhitwell/SlowMovie#137]
**Describe the problem**
Hi, I just got an Inky Impression - got it working, but not in color - image is black and white. I though adding 'mode = color' would do the trick but nothing yet... (Yes, I checked that the .mkv I'm using is a color film) 

omni-epd.conf (in the SlowMovie folder)
```
[Display]
epd = inky.impression
mode = color
```

slowmovie.conf
```
random-frames = True
delay = 240
increment = 4
contrast = 1.0
epd = inky.impression
```

**Platform Information** 
Pi 4 
inky impression 5.7

**Comment by robweber** [comment]
That should have done the trick, but I think you may have mode set in the wrong spot. Try putting the mode under the `[EPD]` part of the config and see if that helps. 

https://github.com/robweber/omni-epd#advanced-epd-control

**Comment by TomWhitwell** [comment]
Ah thank you, that did the trick. 

COLOUR! Wow!
