### ISSUE TITLE
Maximise image / minimise borders

### ISSUE THREAD

**Issue by TomWhitwell** [TomWhitwell/SlowMovie#138]
**Describe the problem**

![image](https://user-images.githubusercontent.com/1890544/191832661-582a0d67-bde7-407a-b94e-18cb8596cb52.jpeg)

**Describe the solution you'd like**
Obviously not a default, but sometimes I'd just like the movie frame to fit the screen without letterboxing - that old-school movies-on-TV effect. I suspect actual pan/scan would be hard so just identifying the borders and cropping into the centre of the image. It looks like ffmpeg has a cropdetect function but I couldn't work out how to use it... 

**Describe alternatives you've considered**
Could be done by editing film files but I prefer to keep them clean.

**Comment by missionfloyd** [comment]
Like this?
![frame](https://user-images.githubusercontent.com/4073789/191893076-63238c0f-c18e-47e0-a35d-0a8c4c6067cf.png)
![framecropped](https://user-images.githubusercontent.com/4073789/191893062-b7d01d5b-070e-483a-b184-9846bac89b61.png)
```python
def generate_frame(in_filename, out_filename, time):
    (
        ffmpeg
        .input(in_filename, ss=time)
        .filter("scale", "iw*sar", "ih")
        .filter("crop", f"ih*({width/height})", "ih")# Crop to aspect ratio of display.
        .filter("scale", width, height, force_original_aspect_ratio=1)
        .filter("pad", width, height, -1, -1)
        .output(out_filename, vframes=1, copyts=None)
        .overwrite_output()
        .run(capture_stdout=True, capture_stderr=True)
    )
```
