### ISSUE TITLE
Anyway to get rid of letterbox format and fill the screen?

### ISSUE THREAD

**Issue by NickAnsy** [TomWhitwell/SlowMovie#14]
Hey guys,
I formatted a video in the exact dimensions of my screen for this.  Wondering what I can do to make this work with the code, or if there's way to do so. 
Thanks

**Comment by TomWhitwell** [comment]
Hi, that's done by this line: 
`        .filter('scale', width, height, force_original_aspect_ratio=1)`
It shouldn't add a letterbox if the video is the right size, but you might want to experiment there, or look at @missionfloyd's version https://github.com/missionfloyd/SlowMovie/blob/master/slowmovie.py

**Comment by TheQwerty** [comment]
I think you'll want to experiment with the `generate_frame` method in particular lines 24/25 where it uses ffmpeg to apply the scale and pad filter.

If your video is the correct dimension I think you may be able to remove the `force_original_aspect_ratio` parameter and skip the pad filter entirely, but I'm not certain.

This seems like a pretty good explanation of the scaling filter: https://trac.ffmpeg.org/wiki/Scaling

**Comment by NickAnsy** [comment]
Thanks guys,
Ill have a look at it and see what I can figure out.
Also, Im getting these streaks in the screen.  Cant figure out why, Ive read about it maybe being the HAT but not sure.

Thanks,

Nick Ansbaugh
Cell: 574-217-6119
nansbaugh@gmail.com



On Dec 3, 2020, at 2:07 PM, Tom Whitwell <notifications@github.com> wrote:


Hi, that's done by this line:
.filter('scale', width, height, force_original_aspect_ratio=1)
It shouldn't add a letterbox if the video is the right size, but you might want to experiment there, or look at @missionfloyd <https://github.com/missionfloyd>'s version https://github.com/missionfloyd/SlowMovie/blob/master/slowmovie.py <https://github.com/missionfloyd/SlowMovie/blob/master/slowmovie.py>

**Comment by NickAnsy** [comment]
How can I be sure my screen is going to sleep? Do you think it could be damaged from not sleeping? I've gone through the code and see it at the end but how can I confirm it sleeps?
