### ISSUE TITLE
Issue with slowmovie.service

### ISSUE THREAD

**Issue by MasonPi** [TomWhitwell/SlowMovie#140]
When doing a fresh install from the automatic setup, I'm getting an error with the slowmovie.service 

cp: cannot stat 'slowmovie.service': No such file or directory
Failed to enable unit: Unit file slowmovie.service does not exist.

Is there any fix for this?

**Comment by robweber** [comment]
Looks like you found an error from when this was recently updated. The template file code from [here](https://github.com/TomWhitwell/SlowMovie/blob/main/Install/install.sh#L93) should also be updated [here](https://github.com/TomWhitwell/SlowMovie/blob/main/Install/install.sh#L111). 

Just "thinking out loud" the best solution would be to make a function for this so it isn't the same code scattered in two spots for future updates. I'll try and update the install file by the end of the weekend (unless someone else beats me to it!). In the meantime you should be able to run this via the command line from the SlowMovie directory to get the service working. 

```
envsubst <slowmovie.service.template > slowmovie.service
sudo mv slowmovie.service /etc/systemd/system
sudo systemctl daemon-reload
sudo systemctl enable slowmovie
```
