### ISSUE TITLE
Waveshare 2.13 V3

### ISSUE THREAD

**Issue by wobblewoo** [TomWhitwell/SlowMovie#144]
Hello. Love this project

I cannot get the newest Waveshare 2.13 V3 to work. I can get it to display when testing here:
https://www.waveshare.com/wiki/Template:Raspberry_Pi_Guides_for_SPI_e-Paper

Is there support for it please?
epd = waveshare_epd.epd2in13_V3

I can see V2 listed here but no V3
https://github.com/robweber/omni-epd/blob/main/README.md#displays-implemented

Many thanks

W

**Comment by wobblewoo** [comment]
Hey, thanks for the reply. Yes it's the plain b/w one, this with V3 on the back.https://thepihut.com/products/eink-screen-2-13-250x122-display-onlyAnd of course I'll test. Great project and write up.Thanks for your time.Wx Sent from Outlook for Android

**Comment by robweber** [comment]
If you could checkout this branch and build the library I've added support based on what I see in the waveshare code. If it works I'll merge it in.

**Comment by wobblewoo** [comment]
Hey Rob. Thanks but i'm new to this and have no idea what that means. Would you mind making it idiot proof for me please?

**Comment by robweber** [comment]
I'll give it a shot - you'll have to do some manual building though. Going to assume you installed using the helper script, so first we'll uninstall the current omni-epd install and then build the new one. On the CLI do the following: 

```
pip3 uninstall omni-epd
omni-epd-test -h
```
The `omni-epd-test` command should __fail__ this just confirms the library is gone. Now clone and build the test branch:

```
git clone https://github.com/robweber/omni-epd.git
cd omni-epd
git checkout -b waveshare_2in13_V3
git pull origin waveshare_2in13_V3
pip3 install --prefer-binary .
```

This will build the new branch, it may take some time but let it run. After that you can try the test display: 

```
omni-epd-test -e waveshare.epd2in13_V3
```

**Comment by wobblewoo** [comment]
Hey Rob.

Huzzah we now have output on the screen, but i had to do it on a fresh install of everything.

Somethings not right though

The output is small and rotated 90 degrees: 
![1](https://user-images.githubusercontent.com/83766046/224696839-ad7e5d05-45cb-4876-9f5a-b9681a2bc01e.jpg)

I rotate it making a file `omni-epd.ini`
`[Display]
rotate=90
# rotate final image written to display by X degrees [0-360]`

It's then orientated correctly but tiny on the screen
![2](https://user-images.githubusercontent.com/83766046/224697381-c594909c-73ef-4dca-ba26-91cbf6aa1c0a.jpg)

So then i try and make it fullscreen adding the line `fullscreen = true` to `slowmovie.conf` i get this:
![3](https://user-images.githubusercontent.com/83766046/224698897-5f15475d-a006-4a4a-a71a-50e7d6586598.jpg)

Odd. So i remove the rotation and get fullscreen but its rotated again.
![4](https://user-images.githubusercontent.com/83766046/224699597-1b17ff82-0b50-4fef-a707-2fbec31338a9.jpg)

**Comment by robweber** [comment]
The rotating thing doesn't surprise me too much. Many of the smaller displays report their [width and height](https://github.com/waveshare/e-Paper/blob/master/RaspberryPi_JetsonNano/python/lib/waveshare_epd/epd2in13_V3.py#L35) such that they expect the display to be vertical. For this one it reports width=122, height=250. It's annoying but the rotation generally solves the problem. The full screen behavior is cropping the image to reduce letterboxing, you should get a full image here but I think the height and width thing might be messing stuff up. 

Does the EPD test utility (with rotation on) also give you a small image?

**Comment by robweber** [comment]
That test utility looks right so I'd call that a success. What are your thoughts? I'd be OK merging this in unless you think it's not performing right.

**Comment by wobblewoo** [comment]
Swapped for a Waveshare 7.5 V2 without any problems. Many thanks again for your help & time.
