### ISSUE TITLE
Install broken due to python changes in Raspbian Bookworm

### ISSUE THREAD

**Issue by JonCellini** [TomWhitwell/SlowMovie#150]
**Describe the problem**
Due to changes in how python functions in Raspbian Bookworm the default install script fails to install the python dependencies due to a change in how that is handled by default.

It gives the following error:

**error: externally-managed-environment**

The script continues but SlowMovie will fail to run as it's dependencies are not properly met.

```
Cloning into '/home/pi/SlowMovie'...
remote: Enumerating objects: 1479, done.
remote: Counting objects: 100% (543/543), done.
remote: Compressing objects: 100% (168/168), done.
remote: Total 1479 (delta 474), reused 375 (delta 375), pack-reused 936
Receiving objects: 100% (1479/1479), 5.55 MiB | 7.96 MiB/s, done.
Resolving deltas: 100% (832/832), done.
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    For more information visit http://rptl.io/venv

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
SlowMovie install/update complete. To test, run 'python3 /home/pi/SlowMovie/slowmovie.py'
Created symlink /etc/systemd/system/multi-user.target.wants/slowmovie.service → /etc/systemd/system/slowmovie.service.
SlowMovie service installed! Use sudo systemctl start slowmovie to test 
```

**Steps to Reproduce**
Install a fresh Raspbian Bookworm image. Run the installer script.

**Platform Information** 
Raspberry Pi 3 model A+
Raspbian Bookworm 2023-10-10 (reproducible on both armhf & arm64)
Python 3.11.2

**Comment by robweber** [comment]
Doing a bit of research on this it seems this is a direct result of [PEP 668](https://peps.python.org/pep-0668/). A good (and short) explanation of it [is here](https://github.com/python/cpython/issues/102134#issuecomment-1445428402). 

The current install script, and manual instructions, have users installing Python packages within the user space. This is discouraged over the user of virtual environments. There are some hacky ways of just removing the `EXTERNALLY-MANGED` file to avoid this error but modifying things to create and use a virtual environment is the proper fix.

**Comment by robweber** [comment]
That error is specifically with the IT8951 EPD drivers. I imagine something in their build process has changed with the Python version on Bookworm. I haven't had time to play with this much myself but do intend on testing it out and making modifications.

**Comment by wobblewoo** [comment]
Im not sure its advised, but after running into this issue, i have found a solution.

Add this to the end of the pip commands:
`--break-system-packages`

`pip3 install "git+https://github.com/waveshare/e-Paper.git#subdirectory=RaspberryPi_JetsonNano/python&egg=waveshare-epd" --break-system-packages`

Source:
https://github.com/python/cpython/issues/102134

```
Here be dragons...read this part at your own risk!
If you're really, really, really sure you want to use pip or another non-system package manager directly on the packages installed by your Linux distribution, you can pass the --break-system-packages flag to pip. However, it will do exactly what it says if you aren't extremely careful, so if you aren't 120% sure you're an expert who knows exactly what you're doing, don't use it. And if you do, don't say I didn't warn you! :)
```

**Comment by wobblewoo** [comment]
After a fresh install on a new Pi (using --break-system-packages on the pip commands) i now get this error, Can anyone help please?
`raspberry@raspberrypi:~/SlowMovie $ python3 slowmovie.py 
Traceback (most recent call last):
  File "/home/raspberry/SlowMovie/slowmovie.py", line 24, in <module>
    from omni_epd import displayfactory, EPDNotFoundError
ModuleNotFoundError: No module named 'omni_epd`

**Comment by robweber** [comment]
Seems like the libraries most likely didn't installed properly. I wouldn't advise using the `--break-system-packages` command and it's not likely to be the long term solution. 

Raspberry Pi OS - Bookworm has only been out for a few weeks so until we've had a chance to update the install instructions please be patient. It's likely some downstream libraries aren't yet supported. You can still get Bullseye from the [archive site](https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2023-05-03/) as that is known to work.

**Comment by wobblewoo** [comment]
That was it, Bullseye worked. Didn't even notice the new version. Dog!

Thankyou

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JonCellini** [comment]
> The current install script, and manual instructions, have users installing Python packages within the user space. This is discouraged over the user of virtual environments. 

Hey Rob,

I agree a venv is the way to go. That doesn't seem like too heavy of a lift for my shell scripting skills, would you guys be open to a contribution of an enhancement to the install script logic to handle this?

**Comment by JonCellini** [comment]
> × Encountered error while trying to install package.
> ╰─> IT8951
> ```

I ran into that issue on Bookworm as well and was able to resolve it a moment ago while working on the PR for moving to a python venv. I'll write up a proper PR for fixing that as well and submit it :)

**Comment by robweber** [comment]
Awesome. The `omni-epd` library is the upstream where that import is happening. Nothing is ever easy is it? https://github.com/robweber/omni-epd

Do you think this will make trouble for < Python 3.11 installs? Might have to raise the min Python version if it won't work downstream.

**Comment by JonCellini** [comment]
I'm testing it now on a real Pi and will submit a PR for that as soon as it's verified to be working reliably as part of the install (I'd fixed my local copy by hand). My python is somewhat shallow but with a virtual environment you can pin the Python version so I don't imagine it should be a problem. I had success with Python 3.11.2 on my local Bookworm install.

**Comment by JonCellini** [comment]
I tested my latest PR commit and it fixes both issues on Bookworm.

**Comment by GregDMeyer** [comment]
Hi all,
Just wanted to call attention to the new commit I just pushed it IT8951---hopefully it will resolve some of the issues you were having!

**Comment by robweber** [comment]
Great - thanks @GregDMeyer!

Once the Waveshare stuff is ironed out to work on Bookworm too we should be able to move #151 along and get this project going on those systems again.

**Comment by robweber** [comment]
I've made some modifications to the `omni-epd` package that I've tested on both Bullseye and Bookworm. Everything seems to build and work on both those systems on my end. I'm testing using a Waveshare 7.5in display, I don't have an IT8951 type display but the library builds so guessing they'll work properly. 

If anyone wants to test this you can [use this branch](https://github.com/robweber/omni-epd/tree/bookworm_updates) and install into a virtual environment in Bookworm. I changed the Waveshare library from the official one to a fork containing fixes for Bookworm specifically. These fixes work on Bullseye as well so nothing should break on existing Bullseye installs. Not the ideal fix but when the official Waveshare repo gets updated it will be a quick swap out to get the original source working again. 

If you're testing this on an existing install the easiest thing to do is create a new virtual environment and then change the omni-epd line in the `requirements.txt` file to reflect the new branch and then install all the requirements normally and run.

```
# change source to this in requirements.txt
git+https://github.com/robweber/omni-epd.git@bookworm_updates#egg=omni-epd

# build
pip3 install -r Install/requirements.txt
```
