### ISSUE TITLE
E-Ink display does not turn off when shutdown Pi

### ISSUE THREAD

**Issue by albyb11** [TomWhitwell/SlowMovie#16]
**Hi everyone!**

I start 'slowmovie' script correctly, I think. The script runnings fine.
But when I try to shutdown the PI via command line (_sudo shutdown now_) or unplugging the power plug, the display doesn't turn off: 

**the last frame played still remain on the screen.**

I've also tried to interrupt the python's script (with _ctrl+c_) and only after I've shutdown again but.. no way.

ps. To clean the display I have to interrupt the python's script and run the 'hello world.py' that I know it runs only for a few seconds before it returning in blank mode (with no image displayed).
But you know, it is only an uncomfortable beginner's workaround.

Any suggest?

Best Regards

**Comment by NickAnsy** [comment]
The image on the screen will stay until it's cleared, regardless of power.

**Comment by albyb11** [comment]
Thx Nick, 

Any damage to the images if they always on In the screen? How can I clean it automatically every shutdown command input?

Best regards at all

**Comment by TomWhitwell** [comment]
No, this is exactly how e-ink works. The image remains until it is changed

**Comment by albyb11** [comment]
Thanks
