### ISSUE TITLE
Possible to adjust image with VCOM value?

### ISSUE THREAD

**Issue by grooverkm** [TomWhitwell/SlowMovie#17]
I have VSMP running with a 7in5_V2 screen; fantastic project!

Is it possible to adjust the VCOM value in order to try and fine tune the image?  I cannot see where this value is set for the particular screen.

**Comment by missionfloyd** [comment]
I don't know if you ever found an answer to this, but that would be something to ask on [Waveshare's repo](https://github.com/waveshare/e-Paper).
