### ISSUE TITLE
Changes in v0.2

### ISSUE THREAD

**Issue by TomWhitwell** [TomWhitwell/SlowMovie#18]
I'm developing a new version in the v0.2-revisions branch 

Changed files: 

**epdconfig.py** 
Include @bassettb [changes](https://github.com/bassettb/e-Paper/blob/fix-spi-closed-issue/RaspberryPi%26JetsonNano/python/lib/waveshare_epd/epdconfig.py)
* Fixes the issues around SPI shutdown and sleep, to ensure that the screen goes into low-power mode between refreshes. 
* Details: https://github.com/waveshare/e-Paper/pull/65 

**epd7in5_V2.py**
Include @dbrant changes 
* Significantly speeds up screen refresh time by writing data in a different way 
* This is for the 7.5 inch screen, but may be adaptable for other screen types 
* It does not require any changes when the screen is called (for example in slowmovie.py) 
* Incidentally seems to work well on my Raspberry Pi Zero W, which seemed to struggle on previous tests, although others report success 
* Details: https://github.com/waveshare/e-Paper/pull/104

**slowmovie.py** 
Include some of @missionfloyd changes 
* Avoids stretched screens 
* Easier to change screen type 
* epd.sleep() is now uncommented and active, reducing power use and potentially avoiding some display issues
* @missionfloyd has made many other changes, but I'm having some trouble incorporating/testing/understanding them, and they assume python3, while my screen is working with python2 
* Details: https://github.com/TomWhitwell/SlowMovie/pull/4 

**Packaging and updates** 
* I'm completely out of my depth in terms of understanding how to package / deploy an update like this 
* I also wonder if there is a much better way to allow people to install slowmovie & dependencies, rather than the git clone approach in the original article
* If you're available to help with this (by which I mean taking it on and releasing it, rather than offering advice), please comment here or email tom@musicthing.co.uk

**Comment by jameslawler** [comment]
Hi, I just wanted to post a comment to say that I have been using the v0.2 branch and it is noticeably faster at refreshing, and also appears to be more stable on my Raspberry Pi zero W.

I am trying to create a forked version of the project that does not require ffmpeg (for users who don't use NOOBs installation). You just provide a folder full of numbered images and it will takes one image at a time at the specified delay. I export the images  on time using ffmpeg on my Windows machine (which is much easier to install) and then FTP them to the Pi.

I also wanted to mention that I am writing a small installation utility that is based on PiVPN / PiHole. So in the end you can just run a shell command and it should install all the dependencies and the program.

I am trying to build it in a way so that the user could choose a version of `SlowMovie` to clone. Either the ffmpeg version or image version. When I have it working with my forked version, feel free to take a look and then I can help adapt `SlowMovie` to make it compatible.

I will post a comment when it is ready if you are interested to take a look. Thanks for the fun project :)

**Comment by tkameroski** [comment]
I gave V0.2 a try but get OSError: [Errno 24] Too many open files after reaching frame 1012.  I was using a short duration of only 5 and an interval of 1 to test it out.
![IMG_7518](https://user-images.githubusercontent.com/76920240/103488642-44f54280-4ddc-11eb-9e8a-950e6f29d617.jpg)

**Comment by robweber** [comment]
I got the too many files open error as well after running for a while. After some trial and error I can confirm it is related to the [SPI fix mentioned above](https://github.com/waveshare/e-Paper/pull/65) (the implementation of the sleep method). 

After reviewing the code changes what is happening is that the ```epd.init()``` method re-opens a SpiDev() object each time. The only time the driver tries to close this is during the ```module_exit()``` function which essentially never gets called. The result is that every update to the device opens a new file and keeps it open. I confirmed this with calls to ```ls -l /proc/PID/fd``` (put the PID of your process in the PID spot). I have a fix which I'm testing but I'm not sure how it affects the update speed as opposed to just doing a full close/open each time as was done previously. Going to let it run for a few days and see.

**Comment by tkameroski** [comment]
Thanks robweber for the info.  It does appear to be the SPI fix to epdconfig.py that is the problem.  I used the main branch version of that file with the 0.2 version of epd7in5_V2.py and it appears to be working.  At least it hasn't encountered a problem yet, after about 1500 frames and counting.

**Comment by TomWhitwell** [comment]
Thanks @robweber I've accepted your pull request, testing your version now

**Comment by missionfloyd** [comment]
What are you having trouble with?

**Comment by missionfloyd** [comment]
What parts were you having trouble with?

**Comment by TomWhitwell** [comment]
> What parts were you having trouble with? Most of it should work with python 2.

Hi, I just tried it again this morning 

- took the latest version of slowmovie.py from your repo, with the comments you just added, added it to my folder as slowmovieMF.py 
- added timeit to imports, and used  timeStart = timeit.default_timer() as line 148 
- Commented out 115, a python3 print call 
- Changed the first line to #!/usr/bin/python

Unfortunately, I got this error - one of those really unhelpful ffmpeg errors 
```

pi@slowmovie:~/SlowMovie $ python slowmovieMF.py
Update interval: 120
Frame increment: 4
Traceback (most recent call last):
  File "slowmovieMF.py", line 158, in <module>
    generate_frame(currentVideo, "/dev/shm/frame.bmp", msTimecode)
  File "slowmovieMF.py", line 48, in generate_frame
    .run(capture_stdout=True, capture_stderr=True)
  File "/usr/local/lib/python2.7/dist-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
```
If I run it under python3 I get an error because the python3 version of ffmpeg hasn't been installed - I think I've tried installing that in the past, and it seemed to break the python2 version. 

Sorry, I feel like this is all really basic python environment stuff, but I don't know enough about it.

**Comment by missionfloyd** [comment]
Tested and working with python 2 https://github.com/missionfloyd/SlowMovie/blob/master/slowmovie-py2.py
(I had to update setuptools for ffmpeg-python to install under python2: `sudo pip install setuptools -U`)

> If I run it under python3 I get an error because the python3 version of ffmpeg hasn't been installed - I think I've tried installing that in the past, and it seemed to break the python2 version.

Python 2/3 and dependencies can coexist
```
sudo apt install python3-pip
sudo pip3 install ffmpeg-python pillow RPi.GPIO spidev numpy
```
pip for python 2, pip3 for python 3

**Comment by qubist** [comment]
I updated this v0.2 branch to work for python3 and I cleaned up the code a bit and clarified some things: https://github.com/qubist/SlowMovie
