### ISSUE TITLE
Inky Impression

### ISSUE THREAD

**Issue by willmartins** [TomWhitwell/SlowMovie#24]
Hi gang, 

I'm keen to give this project a go but I have an Inky Impression EPD. Do you think it's going to be a particularly difficult task to get Tom's code working with this other display? 

I can kind of see what I would need to get stuck into, has anybody else done this project with an Inky display?

Thanks!

**Comment by missionfloyd** [comment]
It should just be a matter of replacing the parts for dithering and displaying the image. There are examples at [pimoroni's repo](https://github.com/pimoroni/inky).

Something like this. I don't have that screen, so I don't know if this works.
https://gist.github.com/missionfloyd/91930dd5d38008366adfab6aeb91c32a
