### ISSUE TITLE
The same movie after each reboot

### ISSUE THREAD

**Issue by flyingangel007** [TomWhitwell/SlowMovie#26]
Hi!

I loaded the new version with the frame-counter and correct movie-changer. This is working perfect now - thanks a lot for this!

But now I have one more problem: I start with "python slowmovie2.py -d 120 -i 24". I thought, that every time I start without a filename (-f xxxx.mp4), an other movie will start - but every time the same movie will start and continue where it ends. How can I change this, to start a random movie after a reboot?

**Comment by qubist** [comment]
Currently if there's no filename specified with `-f`, the code picks the first video file in the Videos directory. You could change this in the code starting on line 71.
