### ISSUE TITLE
Possible noob with ImportError: No module named ffmpeg

### ISSUE THREAD

**Issue by playgroundprodigy** [TomWhitwell/SlowMovie#27]
I've gone through the instructions on medium, googled, and reviewed these issues but am lost. 

I'm receiving the error 

**ImportError: No module named ffmpeg** when attempting to perform the helloworld.py test. From goggling it seems it may be something in regards to differing python versions but I'm honestly a noob in this domain. I've wiped the pi and performed the install twice now with the same results. 

Any tips to resolve?

**Comment by TomWhitwell** [comment]
Hi, sorry to hear that. 
Did you use a NOOBS pre-built SD card?: 
"If you used NOOBs, then ffmpeg and PIL are already installed. Ffmpeg is slightly fiddly to install, but there are plenty of tutorials out there. If you struggle, use NOOBS."

**Comment by playgroundprodigy** [comment]
Tom, thanks for the quick reply. I had previously used the RaspberryPi installer. I started fresh with the NOOBS installer and performed the steps as listed. The first issue begins when attempting to install FF

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-WYSSVj/ffmpeg-python/
pi@raspberrypi:~/SlowMovie $ python helloworld.py
Traceback (most recent call last):
  File "helloworld.py", line 15, in <module>
    import ffmpeg
ImportError: No module named ffmpeg-python.

Based on this StackOverflow article (https://stackoverflow.com/questions/64095094/command-python-setup-py-egg-info-failed-with-error-code-1-in-tmp-pip-build-rn) pip and setuptools needs an upgrade.

Upon following this article and running the following commands the install for FFMPEG-PYTHON appears successful.
sudo python3 -m pip install -U pip
sudo python3 -m pip install -U setuptools

From the looks of things at this point we should be okay - 

Output:
_```
pi@raspberrypi:~/SlowMovie $ sudo python3 -m pip install -U pip
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pip
  Downloading https://files.pythonhosted.org/packages/fe/ef/60d7ba03b5c442309ef42e7d69959f73aacccd0d86008362a681c4698e83/pip-21.0.1-py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 287kB/s
Installing collected packages: pip
  Found existing installation: pip 18.1
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pip'. No files were found to uninstall.
Successfully installed pip-21.0.1
pi@raspberrypi:~/SlowMovie $ sudo python3 -m pip install -U setuptools
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (40.8.0)
Collecting setuptools
  Downloading https://www.piwheels.org/simple/setuptools/setuptools-54.0.0-py3-none-any.whl (784 kB)
     |████████████████████████████████| 784 kB 290 kB/s
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 40.8.0
    Uninstalling setuptools-40.8.0:
      Successfully uninstalled setuptools-40.8.0
Successfully installed setuptools-54.0.0
pi@raspberrypi:~/SlowMovie $ sudo pip install ffmpeg-python
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting ffmpeg-python
  Downloading https://www.piwheels.org/simple/ffmpeg-python/ffmpeg_python-0.2.0-py3-none-any.whl (25 kB)
Collecting future
  Downloading https://www.piwheels.org/simple/future/future-0.18.2-py3-none-any.whl (491 kB)
     |████████████████████████████████| 491 kB 411 kB/s
Installing collected packages: future, ffmpeg-python
Successfully installed ffmpeg-python-0.2.0 future-0.18.2
```_

However, the error persist... I've read this could be due to the instances of python being different but I really don't understand that.

pi@raspberrypi:~/SlowMovie $ python helloworld.py
Traceback (most recent call last):
  File "helloworld.py", line 15, in <module>
    import ffmpeg
ImportError: No module named ffmpeg

Any other thoughts?

**Comment by missionfloyd** [comment]
You;re installing ffmpeg for python3, then running it with python2. Try `python3 slowmovie.py`

**Comment by playgroundprodigy** [comment]
I'm thinking I'll need to reinstall using "sudo python3 setup.py install" as I'm receiving the below waveshare error. Would that make sense? 

```
pi@raspberrypi:/ $ cd ~/SlowMovie
pi@raspberrypi:~/SlowMovie $ python3 helloworld.py
Traceback (most recent call last):
  File "helloworld.py", line 30, in <module>
    from waveshare_epd import epd7in5_V2
ModuleNotFoundError: No module named 'waveshare_epd'
```

**Comment by missionfloyd** [comment]
Yes, you night also need `sudo pip3 install pillow` for PIL

**Comment by playgroundprodigy** [comment]
Man, this is a trip - if only I didn't need the Python3 lol. So I got past the waveshare error by doing the install again with python3. That said, now I've got a missing file with PIL even though it's showing within Python3.  I'm assuming there's not a way to simply install a FFMPEG-PYTHON version that doesn't need PYTHON3 as that seems to be the hiccup here. 
```
pi@raspberrypi:~/SlowMovie $ python3 helloworld.py
/home/pi/SlowMovie/Videos/test.mp4
Traceback (most recent call last):
  File "helloworld.py", line 69, in <module>
    pil_im = Image.open("grab.jpg")
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'grab.jpg'
pi@raspberrypi:~/SlowMovie $ sudo pip3 install pillow 
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (5.4.1)
pi@raspberrypi:~/SlowMovie $ python3 helloworld.py
/home/pi/SlowMovie/Videos/test.mp4
Traceback (most recent call last):
  File "helloworld.py", line 69, in <module>
    pil_im = Image.open("grab.jpg")
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'grab.jpg'
```

**Comment by missionfloyd** [comment]
That error means it cant find the extracted frame.

You don't necessarily need python3, you can install it all using python2 instead.

**Comment by playgroundprodigy** [comment]
If I stick with Python2, what are your thoughts on the initial error I'm seeing even with NOOBS? 

```
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-WYSSVj/ffmpeg-python/
pi@raspberrypi:~/SlowMovie $ python helloworld.py
Traceback (most recent call last):
  File "helloworld.py", line 15, in <module>
    import ffmpeg
ImportError: No module named ffmpeg-python.
```

**Comment by missionfloyd** [comment]
Try updating pip and setuptools as you did before, but use python instead of python3.

`sudo python3 -m pip install -U pip setuptools`

**Comment by playgroundprodigy** [comment]
YOU SIR ARE AMAZING. Hello World is a go. I'm working on a last-minute anniversary gift so you are literally saving the day for me. I'm learning in the fire here lol. That makes complete sense though that I simply needed to update the setup tools. 

Thank you very much! Now to see if I can get our anniversary video in there lol
