### ISSUE TITLE
Beginner Issue

### ISSUE THREAD

**Issue by testataaaa** [TomWhitwell/SlowMovie#30]
Came here through the Make Magazine Article and have been trying to follow the instructions in https://debugger.medium.com/how-to-build-a-very-slow-movie-player-in-2020-c5745052e4e4, but without luck.

The directory seems to be different than in the original write-up?

Would it be possible to clarify for noobs how to install?

Thanks

**Comment by TomWhitwell** [comment]
@missionfloyd @robweber Please let me know if you need me to update any of the documentation in the Medium post.

**Comment by robweber** [comment]
Linking this to current Code Merger - updated instructions will be available then in the README

**Comment by testataaaa** [comment]
Thanks for the replies. Turns out I must have tried to install just as you were updating, as the directory now looks fine.

I am still having an issue. After installing ffmpeg (based on this site: https://snapcraft.io/install/ffmpeg/raspbian), PIL (https://pillow.readthedocs.io/en/stable/) and then sudo pip install ffmpeg-python, I can't run helloworld.py.

Error message:
  File "helloworld.py", line 15, in <module>
    import ffmpeg
ImportError: No module named ffmpeg

Sorry for these questions, I really am a noob who stumbled onto this project through last issue of MakeMagazine,  was hoping for a copy-and-paste-job ;-).

Cheers

**Comment by TomWhitwell** [comment]
Others may have better advice, but you could try `sudo helloworld.py`

**Comment by missionfloyd** [comment]
Are you using python3? Is so, use pip3 instead of pip:
`sudo apt install python3-pip`
`sudo pip3 install ffmpeg-python pillow`

**Comment by testataaaa** [comment]
> Are you using python3? Is so, use pip3 instead of pip:
> `sudo apt install python3-pip`
> `sudo pip3 install ffmpeg-python pillow`

Thanks for the reply, yes I have python3 and used pip3

Look, it might not be worth trying to sort out this issue with me as I don't know what I'm doing. 
But if you do re-make this project at one point (try and install it on a raspberry Pi from scratch),, I'd be interested to know what changes you made to make it work.

Thanks!

**Comment by qubist** [comment]
Hey @testataaaa,

I had the same problem building this recently. Welcome to dependency hell 😇 My advice: use python3. That means you've gotta use `pip3` for all your installations.

[Uninstall and reinstall worked for me](https://github.com/TomWhitwell/SlowMovie/issues/12#issuecomment-739526274) a few times when I got weird ffmpeg errors:
```bash
pip3 uninstall ffmpeg
pip3 uninstall ffmpeg-python
pip3 install ffmpeg
pip3 install ffmpeg-python
```

and then `python3 helloworld.py`

No worries about being a noob hehe. Good on you for building this and working through the accompanying issues 👍

**Comment by missionfloyd** [comment]
ffmpeg itself is installed with `sudo apt install ffmpeg`, not pip.

**Comment by testataaaa** [comment]
> Hey @testataaaa,
> 
> I had the same problem building this recently. Welcome to dependency hell 😇 My advice: use python3. Like missionfloyd said, that means you've gotta use `pip3` for all your installations.
> 
> [Uninstall and reinstall worked for me](https://github.com/TomWhitwell/SlowMovie/issues/12#issuecomment-739526274) a few times when I got weird ffmpeg errors:
> 
> ```shell
> pip3 uninstall ffmpeg
> pip3 uninstall ffmpeg-python
> pip3 install ffmpeg
> pip3 install ffmpeg-python
> ```
> 
> and then `python3 helloworld.py`
> 
> No worries about being a noob hehe. Good on you for building this and working through the accompanying issues 👍

Thanks for the encouragement and the tips.

I wiped everything and re-installed twice, but unfortunately no luck. Might just be what you called the dependency hell, as far as I'm aware everything is updated and upgraded to the latest versions.

Found another Waveshare project to do that is easier (i understand what's happening) so I will come back to this when I am older and wiser.

**Comment by missionfloyd** [comment]
Are you running pip3 with sudo? If not, it may not be able to find the dependencies you install.

**Comment by qubist** [comment]
@testataaaa Just an update: the install instructions have gone through a couple revisions since you ran into this issue. You could try pulling the new code and going through the new instructions now

**Comment by testataaaa** [comment]
> @testataaaa Just an update: the install instructions have gone through a couple revisions since you ran into this issue. You could try pulling the new code and going through the new instructions now

Hey, thanks team!
I just completed a separate project with the waveshare screen, so I now understand the code better.

I think I got stuck on dependencies etc, it just wouldn't click. 
I will try out the new instructions and let you know how it goes for a noob.

**Comment by testataaaa** [comment]
> @testataaaa Just an update: the install instructions have gone through a couple revisions since you ran into this issue. You could try pulling the new code and going through the new instructions now

I just tried it out with the updated instructions and..... it works!

Thanks team for this, really appreciate it. Now to dig in to this and try and understand what's happening ;-).

Great project, well done!
