### ISSUE TITLE
Add Unified Logging

### ISSUE THREAD

**Issue by robweber** [TomWhitwell/SlowMovie#31]
Replace the ```print()``` statements with a unified log file using the Python logging module. The waveshare library already has support for that so we'd capture some of that output too. 

When the program is run as a service a log file has more usefulness than the command line output for monitoring and debugging. 

_Originally posted by @robweber in https://github.com/TomWhitwell/SlowMovie/pull/29#discussion_r605086464_

**Comment by missionfloyd** [comment]
If you run it as a service, all output goes into the journal, viewable with `journalctl -u slowmovie`. This is also why I removed some of the print statements, thousands of lines of "Displaying frame x of y"

**Comment by robweber** [comment]
That's a good point, which may solve this problem. There may be value in a debug flag and then pass all print statements through a function. That way you could debug on the command line but when running normally you wouldn't spam the log. Definitely want some type of solution as this moves more towards a service orientation as opposed to all the command line setup.

**Comment by missionfloyd** [comment]
Another option could be to do it the other way around. Add a [hidden](https://docs.python.org/3/library/argparse.html#help) `--service` argument to suppresses excess output.`

**Comment by missionfloyd** [comment]
I added the `--service` flag to suppress excess messages. The service file will need to be copied again.

**Comment by missionfloyd** [comment]
Okay, here's how I see it. There are three places output can end up: console, systemd journal, and a log file. When running as a service everything printed to the console automatically goes to the journal. When not, it should go to a log file. The logging module adds logging level and such, but that can all be customized. That information probably shouldn't go to the console, but it could go into the log file. Or not. Maybe just timestamps.

Anyway, just my ramblings on the matter.
