### ISSUE TITLE
Video Mode Options

### ISSUE THREAD

**Issue by robweber** [TomWhitwell/SlowMovie#32]
I'll start off by saying I'm likely in the minority here but I think the precedence handling of the arguments and their combinations is very confusing - especially on repeat runs. I think this could be simplified and offer a better user experience. My propsal is to add a ```--mode``` option so that expected behavior can be explained clearly and some arguments can just be eliminated completely. 

I'm basing these observations on what I perceive expected behavior should be; which is: 

* predictable for the end user 
* easy to set up with as minimal arguments as possible
* explainable in ```-h``` or a README in simple terms
* allow seamless playback regardless of program crashes or reboots without having to rely on different arg configurations depending on the situation. 

In other words I should be able to set the system to start playback (via service or @reboot cron job) and not have to guess later on a different argument configuration to continue playback without starting over. 

### Example 1

Assume the following: ```slowmovie.py -f /Video/path.to.file.mp4 --loop```

What will happen is that the program will detect the video does not exist within the directory default ```Videos``` directory and bomb out. Why allow this to happen at all? We just wanted to loop the video. 

### Example 2

Assume the following: ```slowmovie.py -f /Video/path.to.file.mp4 --start 1000```

The video will start, as expected, and start playing at frame 1000. As time goes by we decide reboot the PI or just start/stop the program for some reason. Even though we have saved the current progress we'll start over at frame 1000 again. Very annoying! 

### Example 3

Assume the following: ```slowmovie.py -f Videos/path.to.file.mp4 ```

In this scenerio things start off ok, we start the first video and away we go. After a few weeks we move on to the next video. Again, for some reason the Pi reboots or we just stop the program. At restart we're back to starting at the first video again since the ```-f``` flag trumps any saved progress. 

### Example 4

Assume the following: ```slowmovie.py -f Videos/path.to.file.mp4 ```

Imagine the same scenerio as 3 but now with a different result. We started with video one and moved on to the next video in the directory. After a restart we're now back to playing where we left off with video two. Why? Because we're using a ```-D``` option instead of a ```-f``` option and now the precedence is different. 

## Proposed Fix

While this is all mappable behavior it's really hard to describe these nuances in a ```-h``` listing for the different arguments. Additionally we need special options like ```-l``` for looping that we could probably get rid of. A ```--mode``` flag would separate __file mode__ from __directory mode__ behavior. 

### File mode

In file mode you get exactly what it sounds like. Pass in a ```-f``` option and it will start, and play, that file only forever and ever. Doesn't matter where it is on the file system as long as it can be read. This would allow the ```-l``` option to go away completely. Issues from examples 1 and 3 are also fixed as it's obvious to the user that file mode is meant to only play this file and we don't need any of the directory checks or reboot "what if" issues. 

### Directory Mode

Directory mode works much like things do now but with one big difference. 

1. The ```-f``` flag specifies the file to _start_ with, and that's it. If we move on from this file restarts of the program don't start over here, the ```nowPlaying``` file takes precedence as long as the ```-D``` flag is the same. This fixes the example 3 and 4 issues since you can now use the same program configuration to start playing a directory at a certain file and reliably have it pick up where you left off. 

### Edge Cases

I did not address Example 2 yet. The fix for this is in both program modes (file and directory) we just grab the greater of either ```--start``` or ```nowPlaying``` on reboot. That way you're guaranteed to start there or greater on each re-run. Moving to a new video in directory mode, or restarting the same file in file mode, puts you back at ```--start``` again. 

Another edge case is what if you purposely want to restart the program in directory mode but with a different starting file? Under what I've outlined you'd load the ```nowPlaying``` information and ignore ```--file``` so changes to that arg wouldn't get you anywhere. In this case you'd have to delete ```nowPlaying``` and then restart the program to get a new ```--file``` value to take. I'd consider this an edge case since most people will likely want to start in a directory and just let it play through.

**Comment by TomWhitwell** [comment]
I see two quite different use cases here: 
1) I'm actively logged into the thing via ssh, and I want to run `slowmovie.py` to check that it's working, or might want to change the file or playback speed or whatever 
2) The player is relaunched so the line in /etc/profile runs 'slowmovie.py'  - where the action is almost always 'carry on doing whatever you were doing before power was cycled' 

There is a wrinkle (I think) in that I'm logged into @pi and the machine is still running @root so I'm sending images to the screen and so is the other account. And we're both updating 'now playing' so that's confusing.

**Comment by robweber** [comment]
That would be confusing having two different processes dumping data to the file. In the examples I'm giving I'm trying to draw an inconsistency between when you run via ssh and then again as a service. Why should you need should you need two separate command line strings to accomplish the same goal? You should be able to run the same string either way and have the results be effective. I'm referring to the fact here that you might need ```-f``` when running interactively via SSH but then leave it off for your service command. 

With this proposal my thought would be you'd log in with SSH, change the service command and then just restart the service to get your desired effect. No need to stop the service account, run via SSH manually to "get it started" and then start the service account again. Eventually modifying a config file would be ideal as in the current missionfloyd branch. You'd always have the option of running manually but at least the results would be consistent.

**Comment by qubist** [comment]
I really like this. Splitting the two use-cases of file-looping and directory play-through feels really intuitive to me. 

### A few questions:

> The ```-f``` flag specifies the file to _start_ with, and that's it. If we move on from this file restarts of the program don't start over here, the ```nowPlaying``` file takes precedence as long as the ```-D``` flag is the same. This fixes the example 3 and 4 issues since you can now use the same program configuration to start playing a directory at a certain file and reliably have it pick up where you left off. 

In directory mode, does the `-f` flag only do something if the `nowPlaying` file doesn't exist? And then after that, the program creates a `nowPlaying` file, records the `-f` file into it, starts playing, and then relies on the `nowPlaying` file from then on?

> Moving to a new video in directory mode, or restarting the same file in file mode, puts you back at --start again.

I kinda feel like --start doesn't make so much sense for directory mode. Is --start for skipping the beginning-credits of the movie?  This won't work in a directory where each movie will have different length credits. Simply editing the files might be easier?

### Another thing

I agree with @TomWhitwell that the current way to think about it is that `slowmovie.py` with no arguments means "carry on doing whatever you were doing before power was cycled" and that's what to call on reboot via /etc/profile or cron. Emphasis on the *current* way to think about it. File mode and Directory mode make sense to me for future development.

**Comment by robweber** [comment]
For better or for worse I think my brain is really stuck in this "it should run as a service" mentality. I realize that's not the current setup but to me the whole thing should "feel" like an appliance that just sort of works. I'm sure that's limiting my thinking in some way. I do agree this is more future development thinking. 

Yes, in directory mode the ```-f``` flag would really only do something if ```nowPlaying``` doesn't exist. I think of it more like "where do we start" within a directory and then it's job is kind of done. For _most_ scenarios I don't even think this would be used. I think most people would just point it at a directory and tell it to play. I order my files for play order by using numbers in front of the file name like:

* 1.Video.mp4
* 2.AnotherVideo.mp4

Some discussion of the ```--start``` flag is probably warranted. I think ```--start``` can be a good guess as to where you want to jump in to a film to skip the credits, black screens, etc. If you have the know-how editing the file would prove more accurate. Its a good balance of usability vs user options. I usually set this to about 45 seconds into any video. That usually gets me through most of the intros. In some cases I miss a bit of the actual film but honestly I don't think it's that big of a deal. When it takes weeks/months to play the entire film missing less than a minute isn't that bad.

**Comment by missionfloyd** [comment]
Generally, command line arguments take precedence over config files. The way I have it set up, you can edit nowPlaying, then restart it with `sudo systemctl slowmovie restart` to change files.

**Comment by TomWhitwell** [comment]
Hello @robweber @qubist @missionfloyd just wanted to say I finally installed the new system for the first time on my player - worked really well. 

I just added one line to the Readme instructions to explain that you need to use the config file to determine which file the system will play when running as a service - is that right?

**Comment by qubist** [comment]
Yeah, pretty sure that's right! The service runs `slowmovie.py` with no arguments, so any customizations need to be included in the config file.
