### ISSUE TITLE
Rename main branch from master to main

### ISSUE THREAD

**Issue by qubist** [TomWhitwell/SlowMovie#39]
See https://github.com/github/renaming

Better to do this sooner rather than later (once initial PRs are worked out)

**Comment by robweber** [comment]
Good point - `main` is the standard now so we should probably follow suit. I haven't bothered on older projects but for stuff in active development it's a good practice.

**Comment by missionfloyd** [comment]
Personally, I see no reason to change it.

**Comment by qubist** [comment]
Based on info from [this article](https://docs.github.com/en/github/administering-a-repository/renaming-a-branch), @TomWhitwell would have to do this. Afterwards, cloners can update their local environments according to [these instructions](https://docs.github.com/en/github/administering-a-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes) (same article)

**Comment by missionfloyd** [comment]
It appears it's been done. Kind of pointless, but whatever.
