### ISSUE TITLE
-f never works

### ISSUE THREAD

**Issue by qubist** [TomWhitwell/SlowMovie#44]
Please fill in as much as you can, the more information the easier problems are to solve! 

**Describe the problem**
Running `slowmovie.py` with a -f argument will always throw the error: `slowmovie.py: error: -f can not be used with -R or -D` I should instead be able to specify a file and have it play that file.

**Steps to Reproduce**
```
$ python3 slowmovie.py -f Videos/test.mp4
```

**Platform Information** 
RPi 4 B, Raspbian, NOOBS, python3

**Comment by robweber** [comment]
Well that's interesting. I bet it's because `-D` has a default set [so that if statement](https://github.com/TomWhitwell/SlowMovie/blob/master/slowmovie.py#L93) always comes back as "true" even if it's not specified. As soon as you add the `-f` it enters that block and can't go any further.

**Comment by qubist** [comment]
Maybe this'll all be sorted out when you rework dir mode vs file mode as you've been talking about :) :)
