### ISSUE TITLE
service fails to start

### ISSUE THREAD

**Issue by qubist** [TomWhitwell/SlowMovie#47]
I can't get the service to auto-start on my setup. I followed these instructions in the README

If you want SlowMovie to start automatically when the device is powered on:
* `sudo cp slowmovie.service /etc/systemd/system`
* `sudo systemctl daemon-reload`
* `sudo systemctl enable slowmovie`

But I see "failed" next to slowmovie when running `sudo systemctl` to check out what's going on. Am I just doing something wrong? I haven't used services before.

**Comment by robweber** [comment]
Do you have the exact directory structure for the path? `/home/pi/SlowMovie` ?

**Comment by missionfloyd** [comment]
How to use systemd services:

`sudo systemctl [start|stop|enable|disable|status] slowmovie`

Start, stop, and status are self explanatory. Enable and disable are for autorun.
Log: `journalctl -u slowmovie`

**Comment by robweber** [comment]
Just deleted all the service entries and tried the instructions from the README to double check. It worked for me. We might want to add `sudo systemctl start slowmovie` to the README for people to test that it's working. Info on how to check the log too.

**Comment by tkameroski** [comment]
Into what file do I past  these for autostart on power on?  It would be helpful to be more specific in the readme.

If you want SlowMovie to start automatically when the device is powered on:

sudo cp slowmovie.service /etc/systemd/system
sudo systemctl daemon-reload
sudo systemctl enable slowmovie

It is impressive how much you guys have done in the past few days!

**Comment by qubist** [comment]
Hey @tkameroski. You actually just run these commands in the terminal, one at a time. We're working on sorting this out and updating the Readme with more specific instructions :)

**Comment by qubist** [comment]
> Do you have the exact directory structure for the path? `/home/pi/SlowMovie` ?

Yes:
```
pi@raspberrypi:~/SlowMovie $ pwd
/home/pi/SlowMovie
```

>  Log: `journalctl -u slowmovie`

Thanks a ton! This was what I needed. Running this gave me
```
Apr 06 18:49:50 raspberrypi systemd[1]: Started Slow Movie Player Service.
Apr 06 19:10:01 raspberrypi python3[367]: Update interval: 120
Apr 06 19:10:01 raspberrypi python3[367]: Frame increment: 4
Apr 06 19:10:01 raspberrypi python3[367]: Playing 'test.mp4'
Apr 06 19:10:01 raspberrypi python3[367]: Displaying frame 8 of 'test.mp4'
Apr 06 19:10:01 raspberrypi python3[367]: Displaying frame 12 of 'test.mp4'
Apr 06 19:10:01 raspberrypi python3[367]: Displaying frame 16 of 'test.mp4'
Apr 06 19:10:01 raspberrypi python3[367]: Displaying frame 20 of 'test.mp4'
Apr 06 19:10:01 raspberrypi python3[367]: Displaying frame 24 of 'test.mp4'
Apr 06 19:10:01 raspberrypi python3[367]: Displaying frame 28 of 'test.mp4'
Apr 06 19:10:01 raspberrypi python3[367]: Displaying frame 32 of 'test.mp4'
Apr 06 19:10:01 raspberrypi python3[367]: Displaying frame 36 of 'test.mp4'
Apr 06 19:10:01 raspberrypi python3[367]: Displaying frame 40 of 'test.mp4'
Apr 06 19:10:01 raspberrypi python3[367]: Displaying frame 44 of 'test.mp4'
Apr 06 19:10:01 raspberrypi python3[367]: Displaying frame 48 of 'test.mp4'
Apr 06 19:10:01 raspberrypi python3[367]: Traceback (most recent call last):
Apr 06 19:10:01 raspberrypi python3[367]:   File "/home/pi/SlowMovie/slowmovie.py", line 226, in <module>
Apr 06 19:10:01 raspberrypi python3[367]:     frameCount, framerate, frametime = video_info(currentVideo)
Apr 06 19:10:01 raspberrypi python3[367]:   File "/home/pi/SlowMovie/slowmovie.py", line 72, in video_info
Apr 06 19:10:01 raspberrypi python3[367]:     frameCount = int(videoInfo["streams"][0]["nb_frames"])
Apr 06 19:10:01 raspberrypi python3[367]: KeyError: 'nb_frames'
Apr 06 19:10:01 raspberrypi systemd[1]: slowmovie.service: Main process exited, code=exited, status=1/FAILURE
Apr 06 19:10:01 raspberrypi systemd[1]: slowmovie.service: Failed with result 'exit-code'.
```

I was running an outdated version without .mkv support. When it got to my .mkv file it couldn't crashed. Pulling new code fixed the issue.

Still good to run in to this, to improve the documentation around it a bit.

**Comment by qubist** [comment]
@tkameroski 

> We're working on sorting this out and updating the Readme with more specific instructions :)

Updated now!
