### ISSUE TITLE
-D option always restarts first video

### ISSUE THREAD

**Issue by robweber** [TomWhitwell/SlowMovie#56]
**Describe the problem**
When using the `-D` option, restarts of the program always restart at the first video in the directory; regardless of if a `nowPlaying` file exists. 

Logically I would expect it to start playing the first video and move through the directory. Upon restarting the `nowPlaying` file would load the last played file as long as the directory hasn't changed (ie, file still exists within vids directory). 

**Steps to Reproduce**
1. Have at least 2 videos in the __non-default__ videos directory. I used `/home/pi/Videos`. 

```
# ls of /home/pi/Videos
Video.1.mp4
Video.2.mp4
```

2. Start playing with `-D` and `-f` to force the second video to play. This is to simulate going through the first video and on to the second as part of normal use.  `python slowmovie.py -D /home/pi/Videos -f /home/pi/Vidoes/Video.2.mp4`
3. Wait a while, kill the program
4. Confirm nowPlaying file contents `cat nowPlaying`
5. Restart with just the '-D' option. `python slowmovie.py -D /home/pi/Videos`

The `nowPlaying` file is skipped and the first video restarted. 

**Platform Information** 
N/A

**Comment by missionfloyd** [comment]
`-D` isn't necessary with `-f`. To start at the second file in a directory, just pass that file with `-f`.

The directory is always set to that of the whatever file we're starting with (except in loop mode, where it's irrelevant).
https://github.com/TomWhitwell/SlowMovie/blob/7afc71c14874f7da9bcd6ef51f8ed18675e29dfa/slowmovie.py#L218
This means you can resume like normal with no args.

Maybe this could be made more predictable.

**Comment by missionfloyd** [comment]
b6ae7c7175437193726f5b178ff6d12318cad4cc

**Comment by robweber** [comment]
My example with the -f was meant for re-creation purposes. I always run the program with -D only as I like to play an entire directory. I don't know when the power will go out or what if I shutdown the system too move it? I thinks it's asking alot of people to be messing with the passes in args all the time because it doesn't work predictably.

**Comment by missionfloyd** [comment]
Now it'll resume nowPlaying if `-D` is the same directory. If `-D` is a different directory, it'll start from the beginning of that one.

So running it with just `-D` should work as you described.

**Comment by robweber** [comment]
Just tried it using the same tests as above. Seems to work now as expected, keeps playing the same movie as lone as my args don't change.
