### ISSUE TITLE
Branch Cleanup

### ISSUE THREAD

**Issue by robweber** [TomWhitwell/SlowMovie#57]
As changes are getting made and merged in there are a lot of branches going on in this project repo. As work is completed should/can these be deleted to keep things cleaner? Over time they're going to get more and more out of date so people looking around will wonder why they're there.

**Comment by qubist** [comment]
Sounds good to me. I'm always nervous about hitting the "delete branch" button after merging, but I guess we can always restore them

**Comment by qubist** [comment]
Deleted a bunch of these, I think they were mostly branches I merged. I'll stop leaving behind old branches for future PRs

**Comment by qubist** [comment]
Should we delete `v0.2-revisions`? probably, right?
