### ISSUE TITLE
Portions of images offset

### ISSUE THREAD

**Issue by DustinArmstrong** [TomWhitwell/SlowMovie#61]
**Describe the problem**
On refresh I'm often getting some horizontal shifting of portions of the screen. It's a fresh install and my first time running it. I'm using the service, but it happens when running it manually as well. 

![image](https://user-images.githubusercontent.com/1608205/114638336-65655080-9c99-11eb-990b-4998841421cf.jpeg)

![image](https://user-images.githubusercontent.com/1608205/114638372-744c0300-9c99-11eb-97c6-0fd4e348ac2d.jpeg)

I can sometimes stop and start the service to get a different result without the shifts but it happens periodically again after. The test runs fine best I can tell as well. I have the longest gap between issues after running `Wipe.py`, but I'm also having issues running the `HouseOfDust.py` on occasion as it produces errors. 

```
Traceback (most recent call last):
  File "HouseOfDust.py", line 42, in <module>
    for x in range(rules):
TypeError: 'float' object cannot be interpreted as an integer
```

Running on Raspberry Pi 3B+, same display as tutorials (v2) with the Pi Hat

**Comment by DustinArmstrong** [comment]
Also didn't mean to tag this as a bug yet but can't seem to remove it. Sorry about that.

**Comment by missionfloyd** [comment]
I've fixed the issues with scripts in Extras.

Does the tearing happen with other videos, such as the test file it comes with?

**Comment by DustinArmstrong** [comment]
It is happening with all videos including the test although sometimes intermittently

Here's a shot from the test video

![image](https://user-images.githubusercontent.com/1608205/114712766-75fbe200-9cfe-11eb-88b7-936cfdfe0ad0.jpeg)

I've also removed and re-installed the panel to ensure it wasn't seated improperly. Best I can tell everything is alright.

**Comment by DustinArmstrong** [comment]
Update, I've [submitted an issue with Waveshare](https://github.com/waveshare/e-Paper/issues/154). It appears to happen with their testing software as well. Moving the issue there in the interim and closing this.
