### ISSUE TITLE
How can I change the size of the display? I have a 2in9 display

### ISSUE THREAD

**Issue by fadihh** [TomWhitwell/SlowMovie#62]
**Describe the problem**
Problems should be inconsistencies with how things work or enhancements to the program. For error messages or things not working use a bug report. 

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions that would also fix this issue.

**Comment by missionfloyd** [comment]
We need to add this to the instructions.

To change the display, open `slowmovie.py` and change `epd7in5_V2` on [line 25](https://github.com/TomWhitwell/SlowMovie/blob/3c7d5c97b02ae2992e7a912252899e2ed09a2f21/slowmovie.py#L25) to the correct [driver](https://github.com/waveshare/e-Paper/tree/master/RaspberryPi_JetsonNano/python/lib/waveshare_epd). In your case, one of the following.

Driver | Display
--- | ---
`epd2in9` or `epd2in9_V2` | Black/White
`epd2in9bc` or `epd2in9b_V3` | Black/White/Red or Black/White/Yellow
`epd2in9d` | Flexible

Displays purchased recently are the newer variants (V2/V3).
