### ISSUE TITLE
Waveshare 3in7 errors

### ISSUE THREAD

**Issue by ZubaZ21** [TomWhitwell/SlowMovie#68]
I think the Waveshare 3in7 drivers are non-standard . . . and it's causing the movie not to play.  The display isn't being cleared at all.
**Describe the problem**

```

pi@GeneralPie:~/Projects/SlowMovie $ python3 slowmovie.py -o DEBUG
Picking which video to play...
...trying the --file argument...
...trying the video in the nowPlaying file...
...picked '/home/pi/Projects/SlowMovie/Videos/test.mp4'!
Update interval: 120
Frame increment: 4
Playing 'test.mp4'
Video info: 50 frames, 24.125fps, duration: 00:00:02
This video will take 25.0 minute(s) to play.
Traceback (most recent call last):
  File "slowmovie.py", line 322, in <module>
    epd.init()
TypeError: init() missing 1 required positional argument: 'mode'
```
I changed the line to match the waveshare demo script : epd.init(0)

Ran it again
```
pi@GeneralPie:~/Projects/SlowMovie $ python3 slowmovie.py -o DEBUG
Picking which video to play...
...trying the --file argument...
...trying the video in the nowPlaying file...
...picked '/home/pi/Projects/SlowMovie/Videos/test.mp4'!
Update interval: 120
Frame increment: 4
Playing 'test.mp4'
Video info: 50 frames, 24.125fps, duration: 00:00:02
This video will take 25.0 minute(s) to play.
Displaying frame 0 of test.mp4 (0.0%)
Traceback (most recent call last):
  File "slowmovie.py", line 342, in <module>
    epd.display(epd.getbuffer(pil_im))
AttributeError: 'EPD' object has no attribute 'display'
```

At this point I don't know what to tweak or where to look for what to tweak.

This is the second project that didn't run out of the box as expected.

**Platform Information** 

Display: https://www.waveshare.com/wiki/3.7inch_e-Paper_HAT
Raspberry Pi Zero W Rev 1.1
Linux version 5.10.17+ (dom@buildbot) (arm-linux-gnueabihf-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1403 Mon Feb 22 11:26:13 GMT 2021
Python 2.7.16
Python 3.7.3

**Comment by robweber** [comment]
You are correct - the 3in7 display has some [different methods](https://github.com/waveshare/e-Paper/blob/master/RaspberryPi_JetsonNano/python/lib/waveshare_epd/epd3in7.py) than the standard devices. It takes some additional parameters as part of init() and has some different display methods as well. We're currently [working on a solution](#64 ) to handle non-standard displays - hopefully ready soon.

**Comment by ZubaZ21** [comment]
Rock on!

Thanks

**Comment by qubist** [comment]
> This is the second project that didn't run out of the box as expected.

Seems like they never do

**Comment by robweber** [comment]
@ZubaZ21 - you should be able to follow the instructions and use your 3.7 in display now.  Lookup the display name to use in this table: https://github.com/robweber/omni-epd#displays-implemented

**Comment by ZubaZ21** [comment]
I love the idea of abstracting this.  Very cool.

Pulled it down and ran the test util.
It threw an error.
File
"/usr/local/lib/python3.7/dist-packages/omni_epd/displays/waveshare_display.py",
line 251, in prepare
    self._device.init()
TypeError: init() missing 1 required positional argument: 'mode'

I added a 0 so it became self._device.init(0) as that is what the waveshare
driver requested.

Fired it off again and got the following.

pi@GeneralPie:~ $ omni-epd-test -e waveshare_epd.epd3in7

Loaded waveshare_epd.epd3in7 with width 280 and height 480
Drawing rectangle of width 210.0 and height 360.0
Drawing rectangle of width 105.0 and height 180.0
Drawing rectangle of width 26.25 and height 45.0
Traceback (most recent call last):
  File "/usr/local/bin/omni-epd-test", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/omni_epd/test_utility.py",
line 127, in main
    test.draw()
  File "/usr/local/lib/python3.7/dist-packages/omni_epd/test_utility.py",
line 85, in draw
    self.__draw_on_display(im)
  File "/usr/local/lib/python3.7/dist-packages/omni_epd/test_utility.py",
line 67, in __draw_on_display
    self.epd.display(image)
  File "/usr/local/lib/python3.7/dist-packages/omni_epd/virtualepd.py",
line 202, in display
    self._display(self.__applyConfig(image))
  File
"/usr/local/lib/python3.7/dist-packages/omni_epd/displays/waveshare_display.py",
line 263, in _display
    self._device.display(self._device.getbuffer(image))
AttributeError: 'EPD' object has no attribute 'display'



Let me know if you need further testing.

Aaron

**Comment by robweber** [comment]
Thanks for testing this - I'm going to [move this over](https://github.com/robweber/omni-epd/issues/18) to the omni-epd repo since it's more of an issue with that.
