### ISSUE TITLE
Multiple Video Clips

### ISSUE THREAD

**Issue by robert92679** [TomWhitwell/SlowMovie#7]
First a big THANK YOU to Tom and Bryan for putting this out.  I successfully built a VSMP and really enjoyed it.  Rather than a movie, I use mine to play video clips from my daughter's wedding.  I switched to a portrait orientation by swapping the width and height values on lines 150 and 151.  With this change, portrait video clips fill the display.

My challenge is the VSMP plays only one clip over and over, when there are two clips in the Videos folder.  Both file names are displayed at startup via line 120 ('print (movielist)') and both files have a corresponding '<progress' log file in the logs folder, so the program appears to be registering both clips.

I looked at the code on lines 188-192, which seems like it should increment currentVideo.  But my novice skills can't see the problem.  In my case, the program only plays the first of the two videos in a loop.  Any help would be appreciated!

**Comment by robert92679** [comment]
More troubleshooting...  

a) Either video clip plays when placed in the Videos folder alone, so both video files/filenames appear to be ok.
b) Testing with two files, I monitored the console when it reached the end of the first file.  The attached screenshot shows that it changes to the second filename starting at frame 0, however, the first video file starts again from the beginning and the second file never plays.

![Screenshot from 2020-11-07 14-31-17](https://user-images.githubusercontent.com/74117257/98452957-eb88d400-2108-11eb-94e1-f0ceafb04b5a.png)

**Comment by TheQwerty** [comment]
Just a complete guess because I haven't tried running any of this code, but I think the while loop that starts on line 159 might need to start at 152 because inputVid which is passed to the generate frame method does not get updated within the loop.

My apologies if I'm wrong and just adding noise to this issue.

**Comment by robert92679** [comment]
Thank you so much, that was just the steer I needed.  

Rather than changing the start of the while loop, I copied the inputVid definition from line 153 into the loop at 194 (after currentVideo is updated).  Now the videos cycle as expected at the end of each.

Attached is the revised python file.  Note this is also set up for portrait orientation with the width/height parameters swapped at lines 150 & 151.

[slowmoviePORT.zip](https://github.com/TomWhitwell/SlowMovie/files/5505866/slowmoviePORT.zip)

**Comment by TheQwerty** [comment]
👍  Glad to hear you got it working!

Looking at your revisions I'm afraid you may still have a small issue - though it could easily go unnoticed or not occur for your inputs. The script detects the end of the video by comparing the current position to the total number of frames (line 182) but like `inputVid`, the `frameCount` variable is only set (line 156) before entering the while loop and not updated when switching inputs.

I could see this leading to three possible scenarios:
1. If all videos are the same number of frames everything is miraculously fine.
2. If the starting video has the fewest number of frames it will play that number of frames for all videos, possibly skipping the end of longer videos.
3. If the starting video has more frames than at least one other video then it will depend on what ffmpeg does when asked for a frame beyond the end of the file. It might just grab the last frame or do nothing which should repeat the last frame for the difference in frame counts, or it might throw an exception.

I've done the easy thing and just copied those lines into the block that changes inputs but it is completely untested and there's room for improvement.
[slowmoviePORT-frameCount.zip](https://github.com/TomWhitwell/SlowMovie/files/5513320/slowmoviePORT-frameCount.zip)

Thanks for letting me live vicariously through your work on this until I get around to building my own! 😉

**Comment by robert92679** [comment]
Good catch on that.  Thank you.

My first two video clips were approximately the same length, so I didn't notice the potential problem.  Your revision works great and displays the frame count when each video starts.

Here are a couple pics of the finished product.  I used the RIBBA picture frame from IKEA and an Argon POLY+ case for the Pi.  The case needs a little sanding to provide a clean exit for the ribbon cable and double-sided tape holds it in place.

![VSMP front](https://user-images.githubusercontent.com/74117257/98854772-da450d80-240f-11eb-87be-1fb47be627ca.jpg)
![VSMP rear](https://user-images.githubusercontent.com/74117257/98854804-e7fa9300-240f-11eb-96cf-3376e6b381f0.jpg)

**Comment by TheQwerty** [comment]
That turned out really nice looking - great job!
Now you're probably gonna have to make another as an anniversary gift!

**Comment by NickAnsy** [comment]
Anyone know what causes a screen to do this?![Uploading 99008839...]

**Comment by NickAnsy** [comment]
Anyone know what causes a screen to do this? ![image](https://user-images.githubusercontent.com/73515243/99008879-e4443a80-24fb-11eb-8160-20fa1af7462e.jpeg)
