### ISSUE TITLE
Install script upgrade doesn't update Waveshare library

### ISSUE THREAD

**Issue by qubist** [TomWhitwell/SlowMovie#70]
**Describe the problem**
> Simply running the script to upgrade did not appear to update the waveshare library.

> Since [Waveshare] don't [use version numbers] the version always comes in as 0.0.0. When you re-run the script it sees the same version, assumes the code is the same, and won't rebuild.

> maybe something for us to address as part of the update script. Maybe always uninstall/reinstall waveshare? Takes up time but might save headaches.

— @robweber and @grooverkm in #69

**Steps to Reproduce**
1. Have everything installed with outdated version of Waveshare library
2. Run Install script and select upgrade

Waveshare is not updated to the newest version

**Comment by qubist** [comment]
I think always uninstalling and reinstalling Waveshare is fine. How hard would it be to make a PR over there for them to use version numbers also?

**Comment by robweber** [comment]
Not too hard really, they would just need to include a version number as part of their [setup.py ](https://github.com/waveshare/e-Paper/blob/master/RaspberryPi_JetsonNano/python/setup.py)file. The harder sell would probably be getting them to actually use it and increment it when things change. That would be the _correct_ way to fix this.
