### ISSUE TITLE
Optimal Video File Settings

### ISSUE THREAD

**Issue by ZapRowsdower910** [TomWhitwell/SlowMovie#72]
This is a really cool project and the auto-install script and the docs are pretty good. I was hoping to get some guidance on one area that's lacking some info though. I would like to re-encode my video files to minimize the file size on my SD card, but not so low it would impact the rendering on the eink display. Is there any guidance or perhaps someone ffmpeg settings that ppl are using to re-encode the videos their using on their VSMP to minimize the file size of the file? Basically I want to maximize my available space on my SD card. For example some of my source files are 4k which is obviously overkill for this project and consumes a ton of space. Thanks!

**Comment by missionfloyd** [comment]
The easy way would probably be to use handbrake. Set it to a resolution closer to that of your display. Maybe turn the quality down a few notches, it's not gonna be that noticeable (if at all) on e-paper displays. And the audio isn't being used, so you can remove it.

**Comment by robweber** [comment]
I think those instructions are really good, thanks for sharing. Would you mind if they were incorporated into the documentation here in some way? I was thinking either 1) clone them into the Wiki with a link in the README section of the repo or 2) just a straight link to your instructions. The only downside to 2 is it kind of takes the instructions outside the main repository and makes them harder to keep current. Either way would totally want to give credit to you for putting it all together.

**Comment by missionfloyd** [comment]
The wiki would be good for stuff like this.

**Comment by ZapRowsdower910** [comment]
I agree I think the wiki would be the best way forward. I'm going to need some guidance though as I'm not a big github user tbh. Doesn't seem like I'm able to add to the wiki myself, or I'd go ahead and move it. I can make a PR from my fork to this repo though if that helps. I added a small section to the main readme in my fork that links over to the handbrake docs too in case PR is the preferred method.

**Comment by TomWhitwell** [comment]
Added a wiki, hopefully the maintainers can use it if it's valuable.

**Comment by robweber** [comment]
@ZapRowsdower910 - if it works for you I'll just port your Markdown document over to the wiki - basically cut/paste the way it is. I'll add a shout-out at the bottom to you as the provider as well. That way no messing around with PRs and stuff. The wiki uses markdown too so it should really just be a quick operation. I can clone the pics too as under the hood the wiki is just another Git repo.

**Comment by ZapRowsdower910** [comment]
@robweber ya that works. LMK if you need anything from me, I can provide any help / assistance after my work day is over.

**Comment by robweber** [comment]
Done! Was pretty simply to just drag/drop your stuff in there. https://github.com/TomWhitwell/SlowMovie/wiki/Preparing-Video-Files 

Take a look and see if you have any additional suggestions. If not we can probably close this out.

**Comment by missionfloyd** [comment]
@ZapRowsdower910 It seems you've conflated resolution and quality. See the "constant quality" slider on the video tab. Raising this value lowers the video quality, further reducing file size.
