### ISSUE TITLE
Adjust image brightness

### ISSUE THREAD

**Issue by mcgibbaa** [TomWhitwell/SlowMovie#74]
Some movies are fairly dark and even with contrast set to 1.0, the image can be somewhat difficult to see on e-paper.

Introducing a way to increase the image brightness could help address this. In browsing the code, there is a section I see to adjust the contrast using "enhancer = ImageEnhance.Contrast(pil_im)". In the Pillow documentation, it looks like there is a parallel function for brightness (PIL.ImageEnhance.Brightness(image)). It doesn't appear this allows >1.0, so the original brightness is potentially the max. 

Is there another way to introduce this capability? Or is there another way to shift the image to be lighter?

**Comment by robweber** [comment]
If you are using the latest version checkout the Advanced EPD Control instructions. Since we're using omi-epd for device control you can use that to preprocess images before they are sent to the display.

**Comment by robweber** [comment]
Didn't address your other question. According to the [Pillow docs](https://pillow.readthedocs.io/en/stable/reference/ImageEnhance.html) this is what they have to say regarding the `factor` given to an Enhancement function: 

> Factor 1.0 always returns a copy of the original image, lower factors mean less color (brightness, contrast, etc), and higher values more. There are no restrictions on this value.

It appears that while 1.0 is the original you can certainly go above or below that. I haven't tried myself but the code doesn't seem to toss it out.

**Comment by mcgibbaa** [comment]
Ah, yes - just upgraded to the latest version and see the EPD Controls. This addresses the brightness and more!
