### ISSUE TITLE
Support other dithering algorithms 

### ISSUE THREAD

**Issue by TomWhitwell** [TomWhitwell/SlowMovie#75]
**Describe the <del>problem</del> fun opportunity**

AFAIK, PIL only supports Floyd Steinberg dithering. 

There are many other [interesting dithering algorithms](https://tannerhelland.com/2012/12/28/dithering-eleven-algorithms-source-code.html). A section of Bryan Boyer's [original article that inspired this project](https://medium.com/s/story/very-slow-movie-player-499f76c48b62) is about comparing those algorithms. 

It would be nice to be able to play with those algos here. 

**Describe the solution you'd like**
I suppose this is a config option. Might be interesting to have a test mode (or a different little app) that shows random frames from a movie in x different algorithms, with on-screen text saying which algo is being used. 

**Describe alternatives you've considered**
I researched this a bit at the start of the project, didn't find any easy way to do it in PIL, but I could certainly have missed something.

**Comment by robweber** [comment]
Wonder if something [from this](https://github.com/hbldh/hitherdither), or even incorporating it, would be useful? Looks like a lot of the algorithms from that article are here.

**Comment by missionfloyd** [comment]
Another option would be to use ffmpeg's [paletteuse](https://ffmpeg.org/ffmpeg-filters.html#paletteuse) filter. It doesn't support as many algorithms as hitherdither, but it's faster. Here's an [example](https://github.com/kkroening/ffmpeg-python/issues/193#issuecomment-484808256) of how to use it with ffmpeg-python.

**Comment by missionfloyd** [comment]
We've added this to Omni-EPD via hitherdither. [Here's the options](https://github.com/robweber/omni-epd#advanced-epd-control).

**Comment by TomWhitwell** [comment]
I tried this this evening, had trouble getting it to work. 

I created omni-epd.ini in the SlowMovie folder: 

```
[Display]
rotate=0
dither=bayer
order=4
threshold=[128, 128, 128]
```

Changing Rotate definitely worked, and adding contrast in an Image Enhancements block worked, but I couldn't see any difference with the dithering - bayer 4 should be pretty obvious, it seemed to be floyd-steinberg all the way.  

I also tried 

```
[EPD]
type= omni_epd.mock
mode=bw
```
To save an image but no image was created and the screen refreshed as normal.  `omni-epd-test -e omni_epd.mock`  worked and created a .png file.

**Comment by missionfloyd** [comment]
![mock_output](https://user-images.githubusercontent.com/4073789/120254614-75d08b00-c247-11eb-9023-3aaf8890aa72.png)
Works here. Did it update omni-epd? The current version is 0.2.3. Check `pip3 list`.

As for your other question, if epd is set in slowmovie.conf, it'll use that instead. Maybe we should remove options that are now redundant.

**Comment by TomWhitwell** [comment]
Thank you, the update worked - screen now looks like a game boy camera! 

I had to keep the `epd = waveshare_epd.epd7in5_V2 ` line in slowmovie.conf, or I got an error - `'None' is not a valid EPD name, valid names are: ...` 

I'll experiment with dithering a bit, really great to have this feature

**Comment by robweber** [comment]
We can call that an undocumented feature? :) 

When going to the EPD library we had a discussion on the order of precedence for the `-e` option in `slowmovie.py`. Our compromise was to set the arg to `None` if not passed in and then the library will prompt you to pass in a valid EPD name. This got around having to force people into making the `omni-epd.ini` file as a requirement. The downside is that because we're passing in a value to the `load_display_driver()` method it won't load the ini file value. Manually passed in values always trump config file values. It's an odd quirk of wanting to keep the EPD arg as a SlowMovie value. 

@missionfloyd - I'll make another Issue regarding library updating. I know _why_ it is doing it, however the fix isn't exactly fun.
