### ISSUE TITLE
Screen fade

### ISSUE THREAD

**Issue by dkim777** [TomWhitwell/SlowMovie#79]
Using 7.5 inch screen and experiencing screen fading out issue after continues use for couple weeks.
started to fade from center area and slowing spreading.
if I turn it off for 24hours, it gets better for several hours but eventually fading condition returns.
manual says I should use  epd.sleep function to "turn it off" when not refreshing...
any this code be in between refresh to extend the life of the display?
Thanks.

**Comment by missionfloyd** [comment]
> manual says I should use epd.sleep function to "turn it off" when not refreshing

It [already does that](https://github.com/TomWhitwell/SlowMovie/blob/9cccd393fee3d92711f0773b6e24a3464ae394b6/slowmovie.py#L431). This doesn't sound like a software problem. Could be a temperature issue. Is it exposed to sunlight, or other heat sources?

**Comment by robweber** [comment]
Unfortunately I agree it sounds like a hardware problem - or at the very least an environmental one. I've had a 7.5in screen running for almost a year now without any kind of fading or discoloration issues.

**Comment by dkim777** [comment]
ok, thanks for the replay.
I will check the hardware.
