### ISSUE TITLE
FYI, Raspberry Pi Zero works as well

### ISSUE THREAD

**Issue by kevincloutier** [TomWhitwell/SlowMovie#84]
This may not be news to any one, but since the original tutorial utilizes an RPI 4, I thought I would add a note that I have transitioned to a Zero with no issues. It's been running for the past 24 hours without a bump... As you know, the Zero is easier to mount to the back of a picture frame albeit they are not as ubiquitous as the 4s. 

- Kevin

**Comment by TomWhitwell** [comment]
That’s good news @kevincloutier, I had trouble using a Pi Zero - lockups, half-transitioned screens, but that was with my old code and setup - the new and much improved code / install is probably more reliable. Certainly much neater to mount a Zero. Do let us know if it works long-term

**Comment by kevincloutier** [comment]
48 hours and zero issues..... I'll let it run a few weeks and see if anything pops up (I'm planning on using these for some gifts over the holidays, so I have time to let it run). Also, I was planning on adding a capability to change the movie via GPIO, like with a dip-switch, but the display connects to all of the pins on the Pi, I wonder if it actually uses all of them? Off to find out...

**Comment by tkameroski** [comment]
I ran a Pi Zero from a fresh install starting 6/3 2 PM and it ran without any problems until 2:14 pm today when it stopped displaying new frames.  I ran the logger it in debug mode.  No errors or warnings were logged.  It ended with "Displaying frame" message as it has been doing every 120 seconds for the past 13 days.  The Pi didn't reboot or stop working.  I can still access it through SSH.  The SlowMovie just seemed to freeze.

Are there any logs from the dependencies I can check such as the display driver or FFMPEG to see if they caused the freeze?

I am thinking of scheduling an auto-reboot every night to until a better solution is found.

**Comment by kevincloutier** [comment]
Ok, well, we get closer to a solution! I'm running mine with a 10 minute period and 40 frame advancement. Though your 120 seconds is quite a long time, i wonder if that makes a difference. I guess i will report back in 10 days as to if i am still up and running.

The auto reboot isn't a bad idea though... No one would be the wiser and the memory would reset. Not ideal but we are talking about a raspberry pie picture frame here... :)

**Comment by geekscrapy** [comment]
Anything additional to add since it should have been running a while now? I'm looking to use a Zero for a friends present and I only have a few days to build it, so.... Any hints?!

**Comment by TomWhitwell** [comment]
@geekscrapy Personally, I gave up using the Zero, it worked more reliably with a Pi 4, but I don't have any conclusive theory why it doesn't work.

**Comment by geekscrapy** [comment]
> @geekscrapy Personally, I gave up using the Zero, it worked more reliably with a Pi 4, but I don't have any conclusive theory why it doesn't work.

What didn't work about it? Lock ups?

**Comment by kevincloutier** [comment]
I have had this running on a Zero since my original post with no issues. With that said, I have experienced several power outages this summer due to weather, therefore, the device has not been powered-on since June, but the majority of that time... and I have seen no issues.

**Comment by TomWhitwell** [comment]
> What didn't work about it? Lock ups?
lockups, half-transitioned screens - general weirdness, but that was with my earlier code, the updated code may be more reliable

**Comment by tkameroski** [comment]
I have been running players on two different Pi Zero Ws.  The main problem I had was lock-ups, meaning the display stopped changing to show new frames but the Pi kept running and accessible through SSL.  I mitigated the problem using a small change to the epd driver as described in issue #89.  It doesn't solve the underlying problem but it makes the Pi and display appear to work properly and not freeze.

**Comment by robweber** [comment]
Will leave this open for a bit but trying to transition this info to the wiki for long term use. First pass here: https://github.com/TomWhitwell/SlowMovie/wiki/Hardware

**Comment by robweber** [comment]
Going to close this out as the relevant information should be in the wiki now.
