### ISSUE TITLE
Pi Zero and 6" Waveshare HD

### ISSUE THREAD

**Issue by veebch** [TomWhitwell/SlowMovie#85]
![Slow2001](https://user-images.githubusercontent.com/75116070/122603963-80778680-d075-11eb-9585-4be7b68ca2e3.jpg)

With very little work, I got your code working on my 6" HD waveshare screen. Brilliant code... thanks!

**Comment by robweber** [comment]
Awesome - thanks for sharing. Did you end up modifying any code? Can you share exactly which Waveshare model you have?It would be nice to mark it as "tested" in the [omni-epd library](https://github.com/robweber/omni-epd#displays-implemented).

**Comment by llvllch** [comment]
6inch HD, I changed a few lines... if I do it properly I'll fork and merge

**Comment by qubist** [comment]
Is that your 3D model? Looks great. Can you share?

**Comment by grkngls** [comment]
I bought the waveshare 6inch HD (16 greyscale) because of the refresh-rate about 1second.

But I can't start the vsmp because I can't find a (epd) driver for the 6inch.

Can anyone help me?

**Comment by robweber** [comment]
I found a [python implementation](https://github.com/GregDMeyer/IT8951) for IT8951 devices, like the Waveshare 6in HD. The method calls on it are a lot different than the standard Waveshare libs we're currently using but it looks like all the pieces are there. Could be [integrated with omni-epd](https://github.com/robweber/omni-epd/issues/48).

**Comment by Toksam** [comment]
I'd be curious if this could be expanded to adding any "non-supported" Waveshare screen. I've found all of the drivers from their website but have been hopelessly stuck for over a month on my endeavors. 

I think a general directional push towards what I would even need to do to add a new screen's driver to the omni-epd-library.

**Comment by llvllch** [comment]
@txoof (who must be bored of me tagging him) has been looking at multiple screens at https://github.com/txoof/epd_display

**Comment by txoof** [comment]
@Toksam, It turns out that all of the Waveshare panels are very similar and you can use them (mostly) interchangeably. I've written a [library called epdlib](https://github.com/txoof/epdlib) that makes it pretty easy to use any of the listed screens [here](https://github.com/txoof/epd_display#supported-screens) without modifying anything in the code.

The basic idea is this: instead of hard-coding font sizes and image locations in your code, you create a flexible layout that is calculated at startup to match the dimensions of whatever screen you are using. You can see an example of how the scaling and dynamic layouts work [here](https://github.com/txoof/epdlib#scaling-example).

The epdlib Screen class manages all the writing to the device so you don't have to worry about what device is attached and the weird differences between 2 bit, 8 bit, HD and color screens. 

It's pretty easy to port a project over to epdlib. I'd be happy to help if there is interest.

**Comment by robweber** [comment]
@Toksam - could you be more specific on what you mean with a "non-supported" Waveshare screen? This project already supports a number of Waveshare devices, and a few non-Waveshare, that we could find python drivers for. Looking at the [supported screens list](https://github.com/robweber/omni-epd#displays-implemented), we're currently over 50 supported displays. 

The most called for devices not on our list are IT8951 devices like the Waveshare 6'' HD display. There is a [call for help](https://github.com/robweber/omni-epd/issues/51) on the omni-epd module for help on this if you want to assist in those efforts. Mostly it comes down to access to hardware for testing. There is no shortage of code for how to interact with these screens, we just want to make sure they're tested before adding them. 

As an aside, I read through the code for the epdlib project. There is _some_ overlap between the libraries for sure but I don't think we'd gain anything by porting this to use that project for device communications. They seem to have two different objectives in terms of library design and functionality. Adding the IT8951 devices is actually really trivial assuming we can get them tested.

**Comment by llvllch** [comment]
I'll get it working by the end of the weekend then :)

**Comment by Toksam** [comment]
@txoof @robweber Just some background to help the context of me more. I am designer professionally and code person for fun so I may not be the most technical person but am learning! :) 

Txoof, I am going to take a look through your library and see if it's something that can help me learn. If I have questions or porting is the answer I'd love for a bit of directional feedback so I can at least learn how to do the thing. Haha. However, it seems as Rob thinks there's overlap and might be best to focus on one overall direction.

@robweber The reason I got started down this road of tinkering / learning is that I am trying to help a friend that was doing the initial Slow Movie project but bought one of the 11" screens and that doesn't seem to be supported and I found the drivers from the manufacturer and have tried to even follow their directions with the screen but I can't seem to get that working either. But my plan was to first ensure that I can get the screen running before looking / attempting into how I add that "screen size" into the Omni-epd. 

I guess my questions are around if I can even get the screen working with their drivers (this is an entirely other challenge I have failed at countless times) how does one bring the drivers into Omni-epd and how does one "create a profile" for that particular device so it can be called by the Slow movie program? 

Thanks for all of the help everyone! I appreciate your time! (Also feel free to be like oh dang...this person needs more help than I have time for. I totally get it. :) )

**Comment by robweber** [comment]
Thanks for the explanation. Getting your existing display to do anything with the provided manufacturers code is definitely the first step. For IT8951 devices there is a [branch of omni-epd](https://github.com/robweber/omni-epd/tree/it8951) started that has classes and methods stubbed out for implementation. That would be a good place to start for any kind of integrating. 

Sounds like there are at least a few people interested in working on this. Hopefully some PRs come in!

**Comment by robweber** [comment]
For anyone still monitoring this I've attempted a start at adding support for the IT8951 devices. Currently a base implementation is done but I need testers as I currently do not have a device. My implementation is based of examples in the repo. Those interested please see https://github.com/robweber/omni-epd/pull/57.

**Comment by txoof** [comment]
I'll give it a go. Anything in particular you want us to probe?

**Comment by robweber** [comment]
Basically if it works at all. I tried to copy the test functions from the [IT8951 repo](https://github.com/GregDMeyer/IT8951) to fit the omni-epd syntax. Based on my testing I know the library installs with omni-epd, and will load the driver when you give the right device type. After that - no idea!

If the errors are at all helpful feel free to tweak the code if you're able.

**Comment by txoof** [comment]
@robweber It was a bit of a faff to get numpy installed with the proper `libatlas-base-dev` library, but once I sorted that out, it appeared to work as expected with no errors. Nice work! This will be super helpful for our PaperPi project!

Thanks for the work!

```
$ omni-epd-test -e IT8951.it8951                                     (it8951) X
Loaded IT8951.it8951 with width 1200 and height 825
Drawing rectangle of width 900.0 and height 618.75
Drawing rectangle of width 450.0 and height 309.375
Drawing rectangle of width 112.5 and height 77.34375
Display closed - testing complete
```
![20220222_212705](https://user-images.githubusercontent.com/14262505/155213790-010d7213-6211-4106-9756-8906baf574a1.jpg)
