### ISSUE TITLE
Error after updating following merge of pull #80

### ISSUE THREAD

**Issue by tkameroski** [TomWhitwell/SlowMovie#86]
**Describe the problem**
I tried to update using bash following the merge of pull request #80 but got an error.  See below for the transcript.

**Steps to Reproduce**
pi@raspberrypi:~ $ bash <(curl https://raw.githubusercontent.com/TomWhitwell/SlowMovie/main/Install/install.sh)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5648  100  5648    0     0  23932      0 --:--:-- --:--:-- --:--:-- 23932
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
git is already the newest version (1:2.20.1-2+deb10u3).
ffmpeg is already the newest version (7:4.1.6-1~deb10u1+rpt2).
python3-pip is already the newest version (18.1-5+rpt1).
The following package was automatically installed and is no longer required:
  python-colorzero
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Setting up SPI
SPI already enabled
Existing Install Found - Updating Repo
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 33 (delta 14), reused 30 (delta 12), pack-reused 0
Unpacking objects: 100% (33/33), done.
From https://github.com/TomWhitwell/SlowMovie
   3d47389..614a268  main       -> origin/main
D       Videos/test.mp4
Already on 'main'
Your branch is behind 'origin/main' by 10 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Updating 3d47389..614a268
Fast-forward
 Install/install.sh       | 2 +-
 Install/requirements.txt | 8 ++++----
 README.md                | 3 ++-
 3 files changed, 7 insertions(+), 6 deletions(-)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already up-to-date: ffmpeg-python==0.2.0 in /usr/local/lib/python3.7/dist-packages (from -r /home/pi/SlowMovie/Install/requirements.txt (line 1)) (0.2.0)
Collecting Pillow==8.2.0 (from -r /home/pi/SlowMovie/Install/requirements.txt (line 2))
  Downloading https://www.piwheels.org/simple/pillow/Pillow-8.2.0-cp37-cp37m-linux_armv7l.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 331kB/s
Collecting ConfigArgParse==1.4.1 (from -r /home/pi/SlowMovie/Install/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/e8/a2/b6947a20b67c64b080b999badd231ff4785d1c709a66cfaf8d5e70811a14/ConfigArgParse-1.4.1-py3-none-any.whl
Collecting waveshare-epd from git+https://github.com/waveshare/e-Paper.git#egg=waveshare-epd&subdirectory=RaspberryPi_JetsonNano/python (from -r /home/pi/SlowMovie/Install/requirements.txt (line 4))
  Cloning https://github.com/waveshare/e-Paper.git to /tmp/pip-install-i757qwhk/waveshare-epd
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-i757qwhk/waveshare-epd/RaspberryPi_JetsonNano/python/setup.py", line 17, in <module>
        install_requires=dependencies,
      File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 142, in _install_setup_requires
        dist = MinimalDistribution(attrs)
      File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 134, in __init__
        distutils.core.Distribution.__init__(self, filtered)
      File "/usr/local/lib/python3.7/dist-packages/setuptools/dist.py", line 453, in __init__
        for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
    AttributeError: module 'pkg_resources' has no attribute 'iter_entry_points'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-i757qwhk/waveshare-epd/RaspberryPi_JetsonNano/python
SlowMovie install/update complete. To test, run 'python3 /home/pi/SlowMovie/slowmovie.py'

**Platform Information** 
Pi 4B with 7.5" Waveshare V2

**Comment by robweber** [comment]
Are you sure it might not be due to #81 ? Only reason I ask is that when looking up that error it's often associated with not having an updated `setuptools` lib. We removed the update to setuptools in that PR, as well as moving all installed libs to a local user directory instead of the global python dir. Try manually running `pip3 install setuptools -U` (no sudo) and then the install script again.

**Comment by tkameroski** [comment]
Got the same error after running pip3 install setuptools -U then the install script.  I will wait until I get a problem or want to update again then reinstall from scratch.

**Comment by robweber** [comment]
Finally had time to try this again today on my system (not a clean install though). I removed all waveshare python files and ran `bash <(curl https://raw.githubusercontent.com/TomWhitwell/SlowMovie/main/Install/install.sh)` per the README instructions. Unfortunately I didn't get any of the same errors you did. All libraries downloaded and installed as expected - including the Waveshare one. Running tests with `slowmovie.py` all worked. 

I would suggest doing some web searches for that error `AttributeError: module 'pkg_resources' has no attribute 'iter_entry_points'`; it seems like a pretty common Python error when your build system isn't setup properly.

**Comment by tkameroski** [comment]
If no one else experienced this issue I am going to close it.  Must have been something atypical with my install or update.
