### ISSUE TITLE
where to find epd logs?

### ISSUE THREAD

**Issue by tkameroski** [TomWhitwell/SlowMovie#88]
Where do are the logs for the epd driver and/or omni-epd found?

**Comment by robweber** [comment]
What kinds of logs are you looking for? The Waveshare devices don't really log too much but there is some stuff sent to the debug log. I think in SlowMovie the log settings only apply to SlowMovie program itself as the `-o` log level argument isn't used to configure the global logger. 

So if you're using the default log level of "INFO" you're not going to get any debug logs from other modules. Does that make sense?

**Comment by tkameroski** [comment]
I am looking for the debug logs.  The debug from the epd driver does not show in the slowmovie logs with the -o DEBUG flag and I see that there are log statement in the driver code but I do not know how to turn them on and view them.

thanks

**Comment by robweber** [comment]
I think the issue you're having is that we're not setting the DEBUG value for the global logger but rather just for the slowmovie specific logger. Please try the modifications I made to this branch in my cloned repo: https://github.com/robweber/SlowMovie/tree/global_logging 

You can just replace my `slowmovie.py` file with yours, the rest is the same. When passing in the `-o DEBUG` flag it will now configure this for all loggers in other modules as well. This will only affect console output so you'll have to do it on the command line and watch the output there. I did see both `omni-epd` and the waveshare logging info in the output with these modifications. If it works for you I'll make a PR for the main branch here.

**Comment by tkameroski** [comment]
thanks.
I have been viewing the logs using tail -999 /home/pi/SlowMovie/slowmovie.log
How do I view the console?

**Comment by robweber** [comment]
You'll have to run the program manually using `python3 slowmovie.py -o DEBUG` and whatever other options you need. You can then view the console output directly. I didn't want to push everything to the normal log file since that is for the slowmovie logger only.

**Comment by tkameroski** [comment]
thanks.  Got it.  I stopped the service and ran it manually.  I now see other debug messages from the driver.
