### ISSUE TITLE
Streaks in screen?

### ISSUE THREAD

**Issue by NickAnsy** [TomWhitwell/SlowMovie#9]
Hey guys just trying to figure out if this is my fault or manufacturer defect. One day after having my movie play I started seeing discoloring on the left side of the screen and then large streaks.  The refresh time is set to 150 secs, and I noticed it has the display sleeping which makes me think it was a manufacturers defect. Any help would be appreciated.
Thanks!![image](https://user-images.githubusercontent.com/73515243/99014056-c203ea00-2506-11eb-9665-5749e7620d82.jpeg)

**Comment by Estacaco** [comment]
what happens if you run the test examples on the screen?

**Comment by NickAnsy** [comment]
I'm playing with it now, it looks fine with the demo. It also clears completely.

**Comment by Estacaco** [comment]
and now if you go back to running slowmovie does it work or does it still have lines?

**Comment by NickAnsy** [comment]
It still has lines. So they aren't as bad as the original pic. It was unplugged for a bit.  I think it might have something to do with the sleep command in the code. I think it might have been wrong, not letting the screen sleep and keeping power to it constantly.

**Comment by NickAnsy** [comment]
I think they're coming back after letting it run. So I have no idea.

**Comment by Estacaco** [comment]
Your refresh intervals are too fast!
![Uploading Screenshot_20201113-114225_Samsung Internet.jpg…]()

**Comment by NickAnsy** [comment]
I loaded the demo video and had it running at 180s refresh rate. The streaks only come back when there's slots of white in the frame. At first there was nothing then when it switched to the rear view mirror frame they came back a little bit. Now, having loaded my own video they're back like the first pic. Is it possible I damaged the screen with too fast of a refresh rate?

**Comment by Estacaco** [comment]
Also after some more epaper reading direct sunlight can give you issues with refreshes. I think its possible. I was reading other people that developed vertical lines on epaper due to refreshing too often. Also keep in mind your 12inch screen is actually made of 4 smaller epaper screens

**Comment by Estacaco** [comment]
Id see if you can fix it by making some code that JUST does full refresh of the screen over and over every 180s without actually displaying an image to bring the pixels back (a suggestion i saw regarding lines on epaper screens).

**Comment by missionfloyd** [comment]
I've been using a 2 minute refresh interval for at least a month now, and no damage.

Have you checked if the distortion is present in the image file? (grab.jpg)

**Comment by NickAnsy** [comment]
I haven’t, but I’m using the 12.48in screen.  I’ll check in the morning. It’s been happening on more than one video but I’ve noticed they’re both high res. Not sure what the resolution of the test.mp4 is but that seemed to work better. Still had some white above the top left bit of the screen but not as bad as the others.

**Comment by NickAnsy** [comment]
I have a brand new screen and it's doing the exact same thing. Refresh rate is 210 secs. I'm beyond frustrated, waveshare a customer service is a joke. The only thing I can think of is that it's not actually letting the screen sleep and the constant voltage is messing with it.
