### ISSUE TITLE
Display has large border

### ISSUE THREAD

**Issue by oakey1979** [TomWhitwell/SlowMovie#92]
I'm using SlowMovie with an Inky Impression screen. The image is only displayed in the centre portion of the screen, with around half the display left as a large border. I've updated using the auto script, checked the driver used is Inky.impression and even manually typed the screen dimensions of 600x448 into SlowMovie.py. Is there somewhere else I need to change a setting or value, or is this a new bug?

**Comment by robweber** [comment]
Just to confirm you're using the `-e` flag or manually specified the correct EPD with an `omni-epd.ini` file right? Was this a clean install of the system or did you verify that the Inky Impression display works in some other fashion. There are some tests you can run on just the EPD itself to make sure it's displaying properly before running `slowmovie.py`. 

Last thing - do you have a picture of what it's doing?

**Comment by oakey1979** [comment]
Hi Rob,
I've specified the display in slowmovie.conf (epd = inky.impression), and also tried running 'python3 slowmovie.py -e inky.impression'. Both give the same result where the display works and updates frames but the image is compressed to the centre of the display.I've attached a photo to help.Regarding the omni-epd.ini file, I'm unsure what to change. The guidance shows options for rotation and contrast but I can't see where to specify the display or it's dimensions:
[Display]
rotate=0  # rotate final image written to display by X degrees [0-360]
flip_horizontal=False  # flip image horizontally
flip_vertical=False  # flip image vertically

[Image Enhancements]
contrast=1  # adjust image contrast, 1 = no adjustment
brightness=1  # adjust image brightness, 1 = no adjustment
sharpness=1  # adjust image sharpness, 1 = no adjustmentRegards,Gareth

    On Wednesday, 4 August 2021, 23:15:33 BST, Rob ***@***.***> wrote:  
 
 


Just to confirm you're using the -e flag or manually specified the correct EPD with an omni-epd.ini file right? Was this a clean install of the system or did you verify that the Inky Impression display works in some other fashion. There are some tests you can run on just the EPD itself to make sure it's displaying properly before running slowmovie.py.

Last thing - do you have a picture of what it's doing?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by robweber** [comment]
Sounds like you're doing it right. In SlowMovie using either the conf file or the `-e` option do the same thing. They're just passing that value to the omni-epd display loader to get the right drivers. You can specify the driver in the `omni-epd.ini` file as well but it's not needed if you're using the SlowMovie configuration options. 

Have you tried testing just the display using [the test utility](https://github.com/robweber/omni-epd#display-testing)? You should be able to run `omni-epd-test -e inky.impression`. This will just draw some lines on the display to prove the driver is working. Additionally you can specify `-i` and a path to an image if you want to draw an actual image. 

I believe @missionfloyd has an Inky Impression tested and working. I could be wrong but I know it was a confirmed working display at one point. I did look through the Inky repo real quick but didn't see any major changes to the library in the past 6 months that would have changed any of the calls we're making.

**Comment by oakey1979** [comment]
Yes, I've run the test utility and can see the three rectangles at the positions I'd expect bearing in mind their dimensions. I've also run the Pimoroni toolkit to prove that the whole screen can display an image. Hopefully @missionfloyd comes up with something!

**Comment by robweber** [comment]
That is really weird that the test tool works but then SlowMovie isn't showing the picture right. I recall the Impression having a color border around the screen but it should be really small.

**Comment by missionfloyd** [comment]
Still working as expected over here. Does `/dev/shm/frame.bmp` match what you're seeing?

**Comment by oakey1979** [comment]
Yes, loading a single bmp works as I'd expect. I'm just re-rendering the video file I'd used. Previously I resized it to 600 x 448 to fit the screen. This time, I'll leave it at 720p to see if that makes a difference.

**Comment by oakey1979** [comment]
Nope, that's actually made the video even smaller in the centre of the screen. :(

**Comment by missionfloyd** [comment]
What I mean is, while SlowMovie is running, copy that file from your raspberry pi to see if it displays the same problem.

What are you trying to play on it? Any chance it's encoded with black bars on the sides or top/bottom? If, for instance, a 4:3 video was encoded as 16:9 with pillarboxing, then displayed on a 4:3 screen like the inky impression, will result in a black border all the way around. Some very old DVDs have this problem.

If that's the case, handbrake has a cropping option that should detect and remove black borders by default.
