### ISSUE TITLE
Permission Error Question

### ISSUE THREAD

**Issue by barryanderson** [TomWhitwell/SlowMovie#94]
**Describe the problem**
I installed manually on Ubuntu server and get permission errror when running, the issue is resolved by running with sudo.

` 
Traceback (most recent call last):
  File "slowmovie.py", line 372, in <module>
    epd.prepare()

~/.local/lib/python3.8/site-packages/omni_epd/displays/waveshare_display.py", line 126, in prepare
self._device.init()

~/.local/lib/python3.8/site-packages/waveshare_epd/epd7in5_V2.py", line 162, in init
if (epdconfig.module_init() != 0):

~/.local/lib/python3.8/site-packages/waveshare_epd/epdconfig.py", line 76, in module_init
self.SPI.open(0, 0)

PermissionError: [Errno 13] Permission denied
`

**Platform Information** 
Raspberry Pi 3B+
Ubuntu Server 

Am I missing permissions for the user this is running under?

**Comment by robweber** [comment]
Can you give the version of Ubuntu Server? 

What is most likely happening is that Tom's original implementation used NOOBS, which gives you the Raspberry Pi OS (formally Raspbian). Permissions over the GPIO and SPI interfaces is more than likely different for the built in user on that OS than it is on Ubuntu running on an RPi. 

On my Raspberry Pi OS install running `ls -l /dev/ | grep spi` shows that the SPI interfaces have Read/Write permissions for the `spi` group. The `pi` user is a part of this group out of the box. You could try something similar on your system and see if your local user is a part of the right groups or not. If you don't want to use `sudo` adding your user account to the right groups might help.
