### ISSUE TITLE
Support for other displays

### ISSUE THREAD

**Issue by N317T** [TomWhitwell/SlowMovie#95]
I set up VSMP using an ePaper display that turned out to be a epd7in5_HD rather than the default epd7in5b. I was able to find the correct driver in e-paper/RaspberryPi&JetsonNano/python and edit the code to use it. I changed mSD card and tried reinstalling using the  script here - VSMP appears to be running fine, but the display is not working. 
I have no coding experience and can't find the correct driver, or what to edit to use it.

Is it possible to add an option during install to select an alternative Waveshare screen?

Thanks

**Platform Information**

**Comment by robweber** [comment]
You shouldn't have had to edit any code to use that display. In the README there is a section on using alternate displays. Use the `-e` option to specify the alternative.

**Comment by N317T** [comment]
You are right, don't know how I missed that in the README. It's working perfectly now, thanks for your help
